require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http'); const crypto=require('node:crypto')
const {readVerifiedPublisherEvidence,ledgerInfo}=require('../services/papers/paperPublisherEditionReviewPreflightV6G15')
const PORT=Number(process.env.TEST_API_PORT||5018)
function request(pathname,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+pathname,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
function proposal(){const {manifest}=readVerifiedPublisherEvidence();const entries=manifest.entries.filter(e=>e.grade===9&&String(e.subject).toLowerCase()==='biology');const en=entries.find(e=>e.medium==='English'),ur=entries.find(e=>e.medium==='Urdu');const enl=ledgerInfo('English'),url=ledgerInfo('Urdu');const mk=(entry,ledger,id,edition)=>({status:'INDEPENDENTLY_APPROVED',evidenceId:`edition-${id}`,reviewerId:id,reviewDate:'2026-10-06T10:00:00Z',recordId:entry.recordId,pdfSha256:entry.pdfSha256,reviewedLedgerSha256:ledger.sha256,approvedEdition:edition,downloadStatus:'FULLY_INDEPENDENTLY_VERIFIED',chapterIndexStatus:'INDEPENDENTLY_VERIFIED',exerciseIndexStatus:'INDEPENDENTLY_VERIFIED',rationale:'Independent reviewer verified the pinned source and index evidence.'});return{English:mk(en,enl,9201,'2025-26'),Urdu:mk(ur,url,9202,'2025-26-UM'),bilingualEquivalence:{status:'INDEPENDENTLY_APPROVED',evidenceId:'bilingual-equivalence-http',reviewerId:9203,reviewDate:'2026-10-06T10:00:00Z',enPdfSha256:en.pdfSha256,urPdfSha256:ur.pdfSha256,enLedgerSha256:enl.sha256,urLedgerSha256:url.sha256,rationale:'Independent reviewer compared the pinned English and Urdu edition evidence.'}}}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g15${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G15 QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role};users[key].cookie=await login(email,password,role,code)}
let r=await request('/portal/paper-studio/publisher-review/edition-review-precheck','POST',{},users.teacher.cookie);if(r.status!==403)throw Error(`teacher edition precheck leaked ${r.status}`);console.log('PASS teacher cannot access publisher edition review precheck')
const before=(await c.query('select count(*)::int n from question_bank')).rows[0].n
r=await request('/portal/paper-studio/publisher-review/edition-review-precheck','POST',proposal(),users.admin.cookie);if(r.status!==200||r.json.data?.valid!==true||r.json.policy?.manifestMutated!==false||r.json.policy?.academicQuestionReleased!==false||r.json.policy?.approvalFlagChanged!==false||r.json.policy?.canonicalWriteChanged!==false)throw Error(`admin edition review validation failed ${JSON.stringify(r.json)}`);const after=(await c.query('select count(*)::int n from question_bank')).rows[0].n;if(after!==before)throw Error(`question bank mutated before=${before} after=${after}`);console.log('PASS exact edition review proposal validates read-only with zero Question Bank mutation')
console.log('V6G15_EDITION_HTTP 2/2 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G15_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G15_FAIL',e.stack||e.message);process.exit(1)})
