require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const test=require('node:test')
const assert=require('node:assert/strict')
const {validatePublisherEditionReviewPreflight,readVerifiedPublisherEvidence,ledgerInfo}=require('../services/papers/paperPublisherEditionReviewPreflightV6G15')
function fixture(){const {manifest}=readVerifiedPublisherEvidence();const entries=manifest.entries.filter(e=>e.grade===9&&String(e.subject).toLowerCase()==='biology');const en=entries.find(e=>e.medium==='English'),ur=entries.find(e=>e.medium==='Urdu');const enl=ledgerInfo('English'),url=ledgerInfo('Urdu');const review=(entry,ledger,id,edition)=>({status:'INDEPENDENTLY_APPROVED',evidenceId:`edition-${id}`,reviewerId:id,reviewDate:'2026-10-06T10:00:00Z',recordId:entry.recordId,pdfSha256:entry.pdfSha256,reviewedLedgerSha256:ledger.sha256,approvedEdition:edition,downloadStatus:'FULLY_INDEPENDENTLY_VERIFIED',chapterIndexStatus:'INDEPENDENTLY_VERIFIED',exerciseIndexStatus:'INDEPENDENTLY_VERIFIED',questionGenerationStatus:'PUBLISHED_APPROVED',rationale:'Independent reviewer verified the pinned source and index evidence.'});return{en,ur,enl,url,proposal:{English:review(en,enl,9101,'2025-26'),Urdu:review(ur,url,9102,'2025-26-UM'),bilingualEquivalence:{status:'INDEPENDENTLY_APPROVED',evidenceId:'bilingual-equivalence-20261006',reviewerId:9103,reviewDate:'2026-10-06T10:00:00Z',enPdfSha256:en.pdfSha256,urPdfSha256:ur.pdfSha256,enLedgerSha256:enl.sha256,urLedgerSha256:url.sha256,rationale:'Independent reviewer compared the pinned English and Urdu edition evidence.'}}}}
test('exact independent edition proposal validates without releasing questions',()=>{const f=fixture();const r=validatePublisherEditionReviewPreflight(f.proposal,{forbidReviewerIds:[1]});assert.equal(r.valid,true);assert.equal(r.invariant.questionGenerationStatusChanged,false);assert.equal(r.invariant.liveSeedCountChanged,false);assert.equal(r.policy.manifestMutated,false);assert.equal(r.policy.academicQuestionReleased,false);assert.equal(r.proposedManifestPatch[f.en.recordId].questionGenerationStatus,f.en.questionGenerationStatus);assert.equal(r.proposedManifestPatch[f.ur.recordId].questionGenerationStatus,f.ur.questionGenerationStatus)})
test('wrong reviewed ledger hash fails closed',()=>{const f=fixture();f.proposal.English.reviewedLedgerSha256='f'.repeat(64);assert.throws(()=>validatePublisherEditionReviewPreflight(f.proposal),e=>e.code==='PUBLISHER_EDITION_REVIEW_INVALID'&&e.issues.includes('English:LEDGER_SHA_MISMATCH'))})
test('self reviewer id is rejected',()=>{const f=fixture();assert.throws(()=>validatePublisherEditionReviewPreflight(f.proposal,{forbidReviewerIds:[9102]}),e=>e.code==='PUBLISHER_EDITION_REVIEW_INVALID'&&e.issues.includes('Urdu:REVIEWER_NOT_INDEPENDENT'))})
test('bilingual equivalence must bind to exact pinned PDF hashes',()=>{const f=fixture();f.proposal.bilingualEquivalence.urPdfSha256='e'.repeat(64);assert.throws(()=>validatePublisherEditionReviewPreflight(f.proposal),e=>e.code==='PUBLISHER_EDITION_REVIEW_INVALID'&&e.issues.includes('bilingualEquivalence:UR_PDF_SHA_MISMATCH'))})
