const test=require('node:test')
const assert=require('node:assert/strict')
const {REVIEW_NAMES}=require('../services/papers/paperIndependentReviewIntakeV6G4')
const {buildPublisherPromotionEnvelope,canonicalJson}=require('../services/papers/paperPublisherPromotionEnvelopeV6G10')
function bundle(){const operationalReviews={};for(const [i,name] of REVIEW_NAMES.entries())operationalReviews[name]={status:'INDEPENDENTLY_APPROVED',evidenceId:`ev-${name}`,reviewerId:8000+i,reviewedArtifactSha256:String(i+1).padStart(64,'0'),reviewDate:'2026-10-06T10:00:00Z',scope:{grade:9,subject:'Biology'},result:'APPROVED',rationale:'Independent reviewer checked the exact sealed evidence artifact.',limitations:''};return{operationalReviews}}
function precheck(valid=true){return()=>valid?{valid:true,publisherEvidence:{sha256:'a'.repeat(64),sourceCommit:'abc123'},operationalReviewEvidence:{sha256:'b'.repeat(64)},bindings:REVIEW_NAMES.map((name,i)=>({name,claimedSha256:String(i+1).padStart(64,'0'),expectedSha256:String(i+1).padStart(64,'0'),status:'READY_FOR_INDEPENDENT_REVIEW'})),issues:[]}:{valid:false,issues:['signedPublisherKeyCustody:SEALED_REVIEW_ARTIFACT_NOT_AVAILABLE']}}
test('same valid review bundle produces deterministic envelope hash',()=>{const b=bundle();const a=buildPublisherPromotionEnvelope(b,{buildPublisherPromotionPrecheck:precheck(true)});const c=buildPublisherPromotionEnvelope(JSON.parse(JSON.stringify(b)),{buildPublisherPromotionPrecheck:precheck(true)});assert.equal(a.envelopeSha256,c.envelopeSha256);assert.equal(canonicalJson(a.envelope),canonicalJson(c.envelope));assert.equal(a.envelope.reviews.length,8);assert.equal(a.policy.envelopeIsApproval,false);assert.equal(a.policy.signatureCreated,false);assert.equal(a.nextAction,'REAL_EXTERNAL_PUBLISHER_SIGNATURE_AND_GOVERNED_APPROVAL')})
test('review mutation changes envelope hash',()=>{const b=bundle();const a=buildPublisherPromotionEnvelope(b,{buildPublisherPromotionPrecheck:precheck(true)});b.operationalReviews.isolatedDbCredentialsAndRls.rationale+=' Additional note.';const c=buildPublisherPromotionEnvelope(b,{buildPublisherPromotionPrecheck:precheck(true)});assert.notEqual(a.envelopeSha256,c.envelopeSha256)})
test('invalid G9 precheck blocks envelope creation',()=>{assert.throws(()=>buildPublisherPromotionEnvelope(bundle(),{buildPublisherPromotionPrecheck:precheck(false)}),e=>e.status===409&&e.code==='PUBLISHER_PROMOTION_PRECHECK_BLOCKED'&&e.issues.includes('signedPublisherKeyCustody:SEALED_REVIEW_ARTIFACT_NOT_AVAILABLE'))})
