require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http'); const crypto=require('node:crypto')
const PORT=Number(process.env.TEST_API_PORT||5018)
function request(pathname,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+pathname,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g14${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G14 QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role};users[key].cookie=await login(email,password,role,code)}
let r=await request('/portal/paper-studio/publisher-review/key-custody-precheck','POST',{},users.teacher.cookie);if(r.status!==403)throw Error(`teacher key custody precheck leaked ${r.status}`);console.log('PASS teacher cannot access publisher key custody precheck')
r=await request('/portal/paper-studio/publisher-review/key-custody-precheck','POST',{publicKeyPem:'-----BEGIN PRIVATE KEY-----\nsynthetic-not-a-real-key\n-----END PRIVATE KEY-----',custody:{}},users.admin.cookie);if(r.status!==400||r.json.code!=='PRIVATE_KEY_MATERIAL_FORBIDDEN')throw Error(`private key material was not rejected ${JSON.stringify(r.json)}`);console.log('PASS application server rejects submitted private-key material')
console.log('V6G14_KEY_CUSTODY_HTTP 2/2 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G14_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G14_FAIL',e.stack||e.message);process.exit(1)})
