require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http')
const crypto=require('node:crypto')
const PORT=Number(process.env.TEST_API_PORT||5018)
function req(pathname,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+pathname,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await req('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g19h${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G19 Route QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role,cookie:await login(email,password,role,code)}}
const body={releaseBundle:{privateKeyPem:'forbidden'},signatureRecord:{}}
let r=await req('/portal/paper-studio/publisher-review/release-signature-verify','POST',body,users.teacher.cookie);if(r.status!==403)throw Error(`teacher G19 route expected 403 got ${r.status}`);console.log('PASS teacher cannot access G19 release signature verifier')
r=await req('/portal/paper-studio/publisher-review/release-signature-verify','POST',body,users.admin.cookie);if(r.status!==400||r.json.code!=='PRIVATE_KEY_INPUT_FORBIDDEN')throw Error(`admin G19 route did not enforce private-key rejection ${r.status} ${JSON.stringify(r.json)}`);console.log('PASS admin reaches G19 handler and private-key input is rejected before envelope processing')
console.log('V6G19_RELEASE_SIGNATURE_HTTP 2/2 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G19_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G19_HTTP_FAIL',e.stack||e.message);process.exit(1)})
