const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const crypto=require('node:crypto')
const {buildAcademicPublicationPrecheck,canonical}=require('../services/papers/paperAcademicPublicationPrecheckV6G16')
const sha=v=>crypto.createHash('sha256').update(v).digest('hex')
const EN='1'.repeat(64),UR='2'.repeat(64),SNAP='3'.repeat(64),BASE='8b94fbb99340ca5558c936e7cefe0e628bf083b174bacfc7c4a16d6d5b83f524'
const coverage=JSON.parse(fs.readFileSync(path.join(__dirname,'../services/papers/curriculumReviewedEvidenceV6G2/biology9ExerciseQuestionPageCoverageV6G6.json'),'utf8'))
const mapped=coverage.sources.English.mapped[0]
function reviewer(id,evidenceId){return{reviewerId:id,evidenceId,reviewDate:'2026-10-06T10:00:00Z'}}
function bundle(){const publicationRecords=[{kind:'approved-question',questionEvidenceId:'question-evidence-1',sourceRef:mapped.sourceRef,sourceSnapshotSha256:SNAP}];return{editionReviewProposal:{synthetic:'accepted-by-stub'},conflictDecisions:[{id:'BIO9-C1-THEORY-LAW-001',...reviewer(102,'conflict-1'),status:'INDEPENDENTLY_RESOLVED',reviewedBaseArtifactSha256:BASE,decision:'QUESTION_EXCLUSION_CONFIRMED',rationale:'Independent reviewer confirmed the disputed progression wording must remain excluded.'},{id:'BIO9-C1-MALARIA-CHRONOLOGY-002',...reviewer(103,'conflict-2'),status:'INDEPENDENTLY_RESOLVED',reviewedBaseArtifactSha256:BASE,decision:'ERRATA_CLARIFICATION_REQUIRED',rationale:'Independent reviewer requires official chronology clarification before date questions.'}],approvedQuestion:{...reviewer(104,'question-review-1'),status:'INDEPENDENTLY_APPROVED',questionEvidenceId:'question-evidence-1',sourceSnapshotSha256:SNAP,medium:'English',grade:9,subject:'Biology',sourceRef:mapped.sourceRef,sourcePdfSha256:EN},publicationRecords,signedPublication:{status:'PUBLISHED_APPROVED',trustOrigin:'SERVER_INDEPENDENT_AUDIT',signatureVerification:'PINNED_ED25519_VERIFIED',publicationId:'pub-bio9-1',revision:1,recordsDigest:sha(canonical(publicationRecords)),recordCount:publicationRecords.length,syntheticFixture:false}}}
const deps={validateEditionReview:()=>({architectureVersion:'v6-g15-publisher-edition-review-preflight-1',editionEvidence:{status:'INDEPENDENTLY_APPROVED',evidenceId:'edition-1',reviewerId:101,enPdfSha256:EN,urPdfSha256:UR},invariant:{questionGenerationStatusChanged:false,liveSeedCountChanged:false,questionBankChanged:false}}),readVerifiedEvidence:()=>({evidence:{sourceCommit:'g15-test'},manifestSha256:'4'.repeat(64)})}
test('complete G15-bound academic/publication evidence validates read-only',()=>{const r=buildAcademicPublicationPrecheck(bundle(),deps);assert.equal(r.valid,true);assert.equal(r.approvedQuestionBinding.sourceRef,mapped.sourceRef);assert.equal(r.approvedQuestionBinding.verifiedPhysicalPage,mapped.verifiedPhysicalPage);assert.equal(r.policy.persisted,false);assert.equal(r.policy.questionBankChanged,false);assert.equal(r.policy.canonicalWriteChanged,false)})
test('unmapped question source reference fails closed',()=>{const b=bundle();b.approvedQuestion.sourceRef='UNKNOWN-SOURCE-REF';const r=buildAcademicPublicationPrecheck(b,deps);assert.equal(r.valid,false);assert.ok(r.issues.includes('approvedQuestion:SOURCE_REF_NOT_EXACTLY_MAPPED'))})
test('publication digest tamper fails closed',()=>{const b=bundle();b.signedPublication.recordsDigest='f'.repeat(64);const r=buildAcademicPublicationPrecheck(b,deps);assert.equal(r.valid,false);assert.ok(r.issues.includes('signedPublication:RECORDS_DIGEST_MISMATCH'))})
test('conflict decision must bind to pinned immutable base artifact',()=>{const b=bundle();b.conflictDecisions[0].reviewedBaseArtifactSha256='f'.repeat(64);const r=buildAcademicPublicationPrecheck(b,deps);assert.equal(r.valid,false);assert.ok(r.issues.includes('BIO9-C1-THEORY-LAW-001:BASE_ARTIFACT_SHA_MISMATCH'))})
