require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const { pool } = require('/var/www/apex-backend/config/database')
const bcrypt = require('/var/www/apex-backend/node_modules/bcryptjs')
const http = require('node:http')
const crypto = require('node:crypto')
const PORT = Number(process.env.TEST_API_PORT || 5018)
function request(path,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const req=http.request({host:'127.0.0.1',port:PORT,path:'/api'+path,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>{let json={};try{json=JSON.parse(text)}catch{}resolve({status:res.statusCode,json,headers:res.headers})})});req.on('error',reject);if(raw)req.write(raw);req.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${email} ${r.status}`);return (r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`v6proj${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic V6 Projection QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacherA','teacher'],['teacherB','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role}}
await c.query("insert into teacher_class_assignments(school_id,teacher_user_id,class_name,section,subject,is_active) values($1,$2,'Seven','A','Science',true),($1,$3,'Eight','B','Math',true)",[sid,users.teacherA.id,users.teacherB.id]);for(const u of Object.values(users))u.cookie=await login(u.email,password,u.role,code)
let r=await request('/paper/vault','POST',{paper:{name:'A Science',config:{classLevel:'Seven',section:'A',subject:'Science'}}},users.teacherA.cookie);if(r.status!==201&&r.status!==200)throw Error(`save A ${r.status} ${JSON.stringify(r.json)}`);const idA=String(r.json.paper.id)
r=await request('/paper/vault','POST',{paper:{name:'B Math',config:{classLevel:'Eight',section:'B',subject:'Math'}}},users.teacherB.cookie);if(r.status!==201&&r.status!==200)throw Error(`save B ${r.status}`);const idB=String(r.json.paper.id)
r=await request('/portal/paper-studio/context','GET',null,users.teacherA.cookie);if(r.status!==200||r.json.data?.paperScope!=='own'||r.json.data?.questionScope!=='assigned-approved'||r.json.data?.assignments?.length!==1||r.json.data.assignments[0].className!=='Seven'||!r.json.data.assignments[0].subjects.includes('Science'))throw Error(`teacher context wrong ${JSON.stringify(r.json)}`);console.log('PASS teacher context is signed assignment projection')
r=await request('/portal/paper-studio/papers','GET',null,users.teacherA.cookie);if(r.status!==200||r.json.scope!=='own'||r.json.data.length!==1||String(r.json.data[0].id)!==idA||r.json.data[0].name!=='A Science')throw Error(`teacher own list wrong ${JSON.stringify(r.json)}`);console.log('PASS teacher list contains exactly own paper')
r=await request(`/portal/paper-studio/papers/${idB}`,'GET',null,users.teacherA.cookie);if(r.status!==404)throw Error(`teacher cross-owner lookup leaked ${r.status}`);console.log('PASS cross-teacher direct lookup is non-leaking 404')
r=await request('/portal/paper-studio/papers','GET',null,users.admin.cookie);if(r.status!==200||r.json.scope!=='school'||r.json.data.length!==2)throw Error(`admin list wrong ${JSON.stringify(r.json)}`);console.log('PASS admin sees school-wide paper projection')
r=await request(`/portal/paper-studio/papers/${idA}`,'GET',null,users.admin.cookie);if(r.status!==200||!r.json.data?.document)throw Error('admin paper open failed');console.log('PASS admin can open governed school paper')
r=await request(`/portal/paper-studio/papers/${idA}/document-review`,'GET',null,users.teacherA.cookie);
if(r.status!==200||r.json.review?.family!=='legacy-connect-vault'||r.json.review?.canonicalWriteAllowed!==false||r.json.review?.printApprovalClaim!==false)throw Error(`own paper review boundary failed ${JSON.stringify(r.json)}`);
console.log('PASS owner sees source-preserving legacy review without false canonical authority')
r=await request(`/portal/paper-studio/papers/${idA}/document-review`,'GET',null,users.teacherB.cookie);
if(r.status!==404)throw Error(`cross-owner review leaked ${r.status}`)
console.log('PASS cross-teacher document review is non-leaking 404')
r=await request(`/portal/paper-studio/papers/${idB}/document-review`,'GET',null,users.admin.cookie);
if(r.status!==200||r.json.review?.family!=='legacy-connect-vault')throw Error('admin governed review failed')
console.log('PASS admin can inspect governed school document boundary')
r=await request('/portal/paper-studio/canonical-readiness','GET',null,users.admin.cookie);if(r.status!==200||r.json.data?.ready!==false||r.json.data?.storage?.activePortalRepository!=='paper_vault'||!r.json.data?.blockers?.includes('CANONICAL_REGISTRY_WRITE_DISABLED'))throw Error(`admin canonical readiness wrong ${JSON.stringify(r.json)}`);if(r.json.data?.gates?.canonicalRegistryPresent&&(!r.json.data?.gates?.canonicalRuntimeRoleApproved||!r.json.data?.gates?.tenantRlsApproved||!r.json.data?.gates?.canonicalWriteDefenseApproved))throw Error(`canonical registry physical security gate failed ${JSON.stringify(r.json.data?.gates)}`);console.log('PASS admin sees fail-closed canonical cutover readiness')
r=await request('/portal/paper-studio/canonical-readiness','GET',null,users.teacherA.cookie);if(r.status!==403)throw Error(`teacher storage readiness leaked ${r.status}`);console.log('PASS teacher cannot inspect canonical storage readiness')
const canonicalCounts=async()=>{await c.query('BEGIN');try{await c.query('SET LOCAL ROLE apex_paper_runtime');await c.query("select set_config('app.tenant_id',$1,true)",[String(sid)]);const row=(await c.query('select (select count(*)::int from paper_documents) documents,(select count(*)::int from paper_revisions) revisions')).rows[0];await c.query('ROLLBACK');return row}catch(e){await c.query('ROLLBACK');throw e}};const canonicalBefore=await canonicalCounts()
r=await request(`/portal/paper-studio/canonical-canary/${idA}/preflight`,'GET',null,users.admin.cookie);if(r.status!==200||r.json.data?.eligible!==false||r.json.data?.writeAttempted!==false||r.json.data?.readinessEvaluated!==false||r.json.data?.source?.family!=='legacy-connect-vault'||!r.json.data?.blockers?.includes('CANARY_SOURCE_NOT_APPROVED_AUTHORING_FAMILY'))throw Error(`admin canary preflight failed ${JSON.stringify(r.json)}`);console.log('PASS V6-H0 legacy source fails closed without deep readiness evaluation')
r=await request(`/portal/paper-studio/canonical-canary/${idA}/preflight`,'GET',null,users.teacherA.cookie);if(r.status!==403)throw Error(`teacher canary governance leaked ${r.status}`);console.log('PASS teacher cannot run canonical canary governance preflight')
r=await request(`/portal/paper-studio/canonical-canary/${idA}/plan`,'GET',null,users.admin.cookie);if(r.status!==409||r.json.code!=='CANARY_PLAN_PREFLIGHT_BLOCKED'||!r.json.issues?.includes('CANARY_SOURCE_NOT_APPROVED_AUTHORING_FAMILY'))throw Error(`admin H2 plan did not fail closed ${JSON.stringify(r.json)}`);console.log('PASS V6-H2 plan refuses ineligible legacy source without write')
r=await request(`/portal/paper-studio/canonical-canary/${idA}/plan`,'GET',null,users.teacherA.cookie);if(r.status!==403)throw Error(`teacher H2 plan governance leaked ${r.status}`);console.log('PASS teacher cannot generate canonical H2 canary plan')
const canonicalAfter=await canonicalCounts();if(canonicalAfter.documents!==canonicalBefore.documents||canonicalAfter.revisions!==canonicalBefore.revisions)throw Error(`V6-H0 preflight wrote canonical rows before=${JSON.stringify(canonicalBefore)} after=${JSON.stringify(canonicalAfter)}`);console.log('PASS V6-H0 preflight performs zero canonical writes')
console.log('V6_PROJECTION_GATE 13/13 PASS')
}finally{if(sid){await c.query('delete from paper_vault where school_id=$1',[sid]).catch(()=>{});await c.query('delete from teacher_class_assignments where school_id=$1',[sid]).catch(()=>{});await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('FAIL',e.stack||e.message);process.exit(1)})
