const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const os=require('node:os')
const path=require('node:path')
const crypto=require('node:crypto')
const {verifyCurriculumPublisherEvidence,assertReviewedPreflight}=require('../services/papers/paperCurriculumPublisherEvidenceV6G')
const sha=b=>crypto.createHash('sha256').update(b).digest('hex')
const write=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n')
const H='a'.repeat(64),U='b'.repeat(64)
function completeFixture(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'v6g-publisher-'))
 const manifest={schemaVersion:'assps-official-manifest-v1',authority:'PECTAA',liveSeedCount:24,entries:[
  {recordId:'en-bio9',grade:9,subject:'Biology',medium:'English',pdfSha256:H,pdfUrl:'https://official.example/en.pdf',downloadStatus:'FULLY_INDEPENDENTLY_VERIFIED',edition:'2025-26',chapterIndexStatus:'INDEPENDENTLY_VERIFIED',exerciseIndexStatus:'INDEPENDENTLY_VERIFIED',questionGenerationStatus:'PUBLISHED_APPROVED'},
  {recordId:'ur-bio9',grade:9,subject:'Biology',medium:'Urdu',pdfSha256:U,pdfUrl:'https://official.example/ur.pdf',downloadStatus:'FULLY_INDEPENDENTLY_VERIFIED',edition:'2025-26',chapterIndexStatus:'INDEPENDENTLY_VERIFIED',exerciseIndexStatus:'INDEPENDENTLY_VERIFIED',questionGenerationStatus:'PUBLISHED_APPROVED'},
 ]}
 const dry={stagedRealQuestionCount:24,wouldInsert:24}
 const technical={schemaVersion:'assps-biology9-source-reacquisition-evidence-v1',scope:{grade:9,subject:'Biology'},sources:{en:{catalogRecordId:'en-bio9',pdfSha256:H,matchesEvidenceLedger:true},ur:{catalogRecordId:'ur-bio9',pdfSha256:U,matchesEvidenceLedger:true}},approval:{binaryIntegrityVerified:true,ledgerBindingVerified:true,chapterIndexIndependentApproval:false,exerciseIndexIndependentApproval:false,bilingualEditionEquivalenceApproved:false,academicQuestionReleaseApproved:false,productionPublisherApproved:false},openIssues:['technical evidence does not self-approve production']}
 const mf=path.join(dir,'official.json'),df=path.join(dir,'dry.json'),tf=path.join(dir,'technical.json');write(mf,manifest);write(df,dry);write(tf,technical)
 const reviews={};for(const n of ['signedPublisherKeyCustody','independentSubjectGrantLiveSource','isolatedDbCredentialsAndRls','institutionalBackupRestore','teacherStudentResponsePrivacy','multiInstanceIntentSafety','bilingualPrintWordPdfParity','canaryRollbackApproved'])reviews[n]={status:'INDEPENDENTLY_APPROVED',evidenceId:`ev-${n}`,reviewerId:101}
 const evidence={architectureVersion:'v6-g-curriculum-publisher-evidence-1',evidenceOnly:true,approvalClaim:false,sourceCommit:'1'.repeat(40),sourceManifestSha256:sha(fs.readFileSync(mf)),dryRunReportSha256:sha(fs.readFileSync(df)),technicalSourceReacquisitionSha256:sha(fs.readFileSync(tf)),authority:'PECTAA',publicationScope:{grade:9,subject:'Biology'},counts:{catalogEntries:2,verifiedPdfHashes:2,chapterIndexesReady:2,exerciseIndexesReady:2,questionGenerationUnblocked:2,stagedRealQuestionCount:24,wouldInsert:24,approvedQuestionCount:24},releaseState:{liveImportAuthorized:true,academicSignoffComplete:true,bilingualSignoffComplete:true,tenantScopedBankSnapshotReviewed:true,publisherKeyCustodyApproved:true,institutionRosterBindingApproved:true},editionEvidence:{status:'INDEPENDENTLY_APPROVED',evidenceId:'edition-pair-1',reviewerId:102,enPdfSha256:H,urPdfSha256:U},signedPublication:{status:'PUBLISHED_APPROVED',trustOrigin:'SERVER_INDEPENDENT_AUDIT',signatureVerification:'PINNED_ED25519_VERIFIED',publicationId:'pub-bio9-1',revision:1,recordsDigest:'c'.repeat(64),recordCount:24,syntheticFixture:false},operationalReviews:reviews,openIssues:[],artifacts:{officialSourceManifest:{file:'official.json',sha256:sha(fs.readFileSync(mf))},dryRunReport:{file:'dry.json',sha256:sha(fs.readFileSync(df))},sourceReacquisitionEvidence:{file:'technical.json',sha256:sha(fs.readFileSync(tf))}}}
 const ef=path.join(dir,'evidence.json');write(ef,evidence)
 return {dir,ef,evidence,manifest,dry,technical,env:{PAPER_CURRICULUM_PUBLISHER_EVIDENCE_PATH:ef,PAPER_CURRICULUM_PUBLISHER_EVIDENCE_SHA256:sha(fs.readFileSync(ef)),PAPER_CURRICULUM_PUBLISHER_SOURCE_COMMIT:evidence.sourceCommit}}
}

test('reviewed Phase3AB readiness source is byte pinned',()=>assert.equal(assertReviewedPreflight(),true))
test('complete independent publisher evidence validates but does not itself authorize production',async()=>{const f=completeFixture();try{const r=await verifyCurriculumPublisherEvidence({env:f.env});assert.equal(r.valid,true);assert.deepEqual(r.issues,[]);assert.equal(r.preflightStatus,'EVIDENCE_COMPLETE_NOT_AUTHORIZED');assert.equal(r.approvedQuestionCount,24)}finally{fs.rmSync(f.dir,{recursive:true,force:true})}})
test('manifest tamper fails even when approval coordinates remain unchanged',async()=>{const f=completeFixture();try{fs.appendFileSync(f.ef,' ');const r=await verifyCurriculumPublisherEvidence({env:f.env});assert.equal(r.valid,false);assert.ok(r.issues.includes('publisher evidence manifest hash mismatch'))}finally{fs.rmSync(f.dir,{recursive:true,force:true})}})
test('source artifact tamper and technical evidence tamper both fail closed',async()=>{const f=completeFixture();try{fs.writeFileSync(path.join(f.dir,'official.json'),'{}');let r=await verifyCurriculumPublisherEvidence({env:f.env});assert.equal(r.valid,false);assert.ok(r.issues.some(x=>x.includes('official source manifest artifact hash mismatch')))}finally{fs.rmSync(f.dir,{recursive:true,force:true})}
 const g=completeFixture();try{g.technical.sources.ur.pdfSha256='f'.repeat(64);write(path.join(g.dir,'technical.json'),g.technical);g.evidence.artifacts.sourceReacquisitionEvidence.sha256=sha(fs.readFileSync(path.join(g.dir,'technical.json')));g.evidence.technicalSourceReacquisitionSha256=g.evidence.artifacts.sourceReacquisitionEvidence.sha256;write(g.ef,g.evidence);g.env.PAPER_CURRICULUM_PUBLISHER_EVIDENCE_SHA256=sha(fs.readFileSync(g.ef));const r=await verifyCurriculumPublisherEvidence({env:g.env});assert.equal(r.valid,false);assert.ok(r.issues.includes('source reacquisition ur identity mismatch'))}finally{fs.rmSync(g.dir,{recursive:true,force:true})}})
test('missing independent review and fake signed publication fail closed',async()=>{const g=completeFixture();try{g.evidence.operationalReviews.canaryRollbackApproved.status='PENDING';g.evidence.signedPublication.signatureVerification='SELF_ASSERTED';write(g.ef,g.evidence);g.env.PAPER_CURRICULUM_PUBLISHER_EVIDENCE_SHA256=sha(fs.readFileSync(g.ef));const r=await verifyCurriculumPublisherEvidence({env:g.env});assert.equal(r.valid,false);assert.ok(r.preflightBlockers.includes('GENUINE_SIGNED_CURRICULUM_PUBLICATION_MISSING'));assert.ok(r.preflightBlockers.some(x=>x.includes('CANARYROLLBACKAPPROVED')))}finally{fs.rmSync(g.dir,{recursive:true,force:true})}})
test('current production evidence bundle is objectively blocked but source reacquisition identity is valid',async()=>{const env={PAPER_CURRICULUM_PUBLISHER_EVIDENCE_PATH:'/root/secure-archive/apex-paper-v6g-20261005/curriculum-publisher-evidence.json',PAPER_CURRICULUM_PUBLISHER_EVIDENCE_SHA256:'ac98f296f98f69ec9dadedd3021dffc90d614546151bb01ccdcea2be4487b7ca',PAPER_CURRICULUM_PUBLISHER_SOURCE_COMMIT:'d6b294db53a9aa5a8f19c6bae5ecbb673996be5c'};const r=await verifyCurriculumPublisherEvidence({env});assert.equal(r.valid,false);assert.equal(r.approvedQuestionCount,0);assert.ok(r.preflightBlockers.includes('NO_APPROVED_LIVE_ACADEMIC_RECORDS'));assert.ok(r.preflightBlockers.includes('EN_OFFICIAL_PDF_NOT_APPROVED'));assert.ok(r.preflightBlockers.includes('UR_EDITION_NOT_APPROVED'));assert.ok(r.preflightBlockers.includes('EN_CHAPTER_INDEX_PENDING'));assert.ok(r.preflightBlockers.includes('UR_EXERCISE_INDEX_PENDING'));assert.ok(!r.preflightBlockers.includes('SCOPE_MISSING'));assert.ok(!r.issues.some(x=>x.includes('source reacquisition')&&x.includes('mismatch')));assert.ok(r.issues.some(x=>x.includes('no independently approved questions')))})
