require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http')
const crypto=require('node:crypto')
const PORT=Number(process.env.TEST_API_PORT||5054)
const BASE='/api'
const request=(url,method='GET',body=null,cookie='')=>new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const req=http.request({hostname:'127.0.0.1',port:PORT,path:BASE+url,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:8000},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{let json;try{json=JSON.parse(out)}catch{json={raw:out.slice(0,200)}}resolve({status:res.statusCode,json,headers:res.headers})})});req.on('error',reject);if(raw)req.write(raw);req.end()})
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers?.['set-cookie']||[]).map?.(x=>x.split(';')[0]).join('; ')||''}
async function main(){const db=await pool.connect();let sid;try{
 const suf=crypto.randomBytes(5).toString('hex'),code='g34'+suf,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10)
 sid=(await db.query("INSERT INTO schools(name,code,status,tenant_id) VALUES('Synthetic G34 QA',$1,'active',$1) RETURNING id",[code])).rows[0].id
 const users={}
 for(const [key,role] of [['teacherA','teacher'],['teacherB','teacher'],['admin','admin']]){const email=`${key}-${suf}@invalid.example`;const id=(await db.query('INSERT INTO users(school_id,tenant_id,name,email,role,password,is_active) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING id',[sid,code,key,email,role,hash])).rows[0].id;const lr=await request('/auth/login','POST',{email,password,role,school_code:code});const sc=lr.headers?.['set-cookie'];const cookie=Array.isArray(sc)?sc.map(x=>x.split(';')[0]).join('; '):'';if(lr.status!==200||!cookie)throw Error(`login ${key} failed ${lr.status}`);users[key]={id,email,cookie}}
 const payload={name:'G34 Original',config:{className:'1',subject:'English',language:'english'},mcq:[{id:'q1',en:'One?',options:['A','B','C','D']}],mcq_marks:1}
 const id=(await db.query("INSERT INTO paper_vault(school_id,owner_user_id,name,class_name,subject_name,status,payload) VALUES($1,$2,'G34 Original','1','English','draft',$3::jsonb) RETURNING id",[sid,users.teacherA.id,JSON.stringify(payload)])).rows[0].id
 let r=await request(`/portal/paper-studio/papers/${id}/document-review`,'GET',null,users.teacherA.cookie);if(r.status!==200)throw Error(`review failed ${r.status} ${JSON.stringify(r.json)}`);const rev1=Number(r.json.revision),hash1=String(r.json.review?.snapshotHash||'');if(rev1!==1||!/^[a-f0-9]{64}$/.test(hash1))throw Error('initial token invalid')
 r=await request(`/portal/paper-studio/papers/${id}/metadata`,'PATCH',{name:'G34 Renamed',expectedRevision:rev1,expectedSnapshotHash:hash1},users.teacherA.cookie);if(r.status!==200||r.json.data?.revision!==2||r.json.data?.snapshotHash!==hash1||r.json.data?.name!=='G34 Renamed')throw Error(`rename failed ${r.status} ${JSON.stringify(r.json)}`);console.log('PASS guarded rename increments revision and preserves snapshot hash')
 r=await request(`/portal/paper-studio/papers/${id}/metadata`,'PATCH',{name:'Stale Rename',expectedRevision:1,expectedSnapshotHash:hash1},users.teacherA.cookie);if(r.status!==409||r.json.code!=='STALE_REVISION')throw Error(`stale rename not rejected ${r.status} ${JSON.stringify(r.json)}`);console.log('PASS stale rename rejected 409')
 r=await request(`/portal/paper-studio/papers/${id}/metadata`,'PATCH',{name:'Cross Teacher',expectedRevision:2,expectedSnapshotHash:hash1},users.teacherB.cookie);if(r.status!==404)throw Error(`cross-teacher rename leaked ${r.status}`);console.log('PASS cross-teacher rename non-leaking 404')
 r=await request(`/portal/paper-studio/papers/${id}`,'DELETE',{expectedRevision:1,expectedSnapshotHash:hash1},users.teacherA.cookie);if(r.status!==409||r.json.code!=='STALE_REVISION')throw Error(`stale delete not rejected ${r.status} ${JSON.stringify(r.json)}`);console.log('PASS stale delete rejected 409')
 r=await request(`/portal/paper-studio/papers/${id}`,'DELETE',{expectedRevision:2,expectedSnapshotHash:hash1},users.teacherA.cookie);if(r.status!==200||r.json.data?.deleted!==true||r.json.data?.revision!==3||r.json.data?.snapshotHash!==hash1)throw Error(`guarded delete failed ${r.status} ${JSON.stringify(r.json)}`);console.log('PASS guarded delete increments revision and soft-deletes')
 r=await request(`/portal/paper-studio/papers/${id}`,'GET',null,users.teacherA.cookie);if(r.status!==404)throw Error(`deleted paper still projected ${r.status}`);console.log('PASS deleted paper no longer projects')
 const rows=await db.query("SELECT revision,event_kind,payload_hash FROM paper_vault_revision_history WHERE school_id=$1 AND paper_id=$2 ORDER BY revision",[sid,id]);if(rows.rows.length!==3||rows.rows[0].event_kind!=='baseline_capture'||rows.rows[1].event_kind!=='v6d_guarded_rename'||rows.rows[2].event_kind!=='v6d_guarded_delete'||rows.rows.some(x=>x.payload_hash.trim()!==hash1))throw Error(`journal mismatch ${JSON.stringify(rows.rows)}`);console.log('PASS immutable journal records baseline, rename, delete')
 console.log('G34_VAULT_METADATA_HTTP 7/7 PASS')
}finally{if(sid){await db.query('DELETE FROM paper_vault_revision_history WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM paper_vault WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM users WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM schools WHERE id=$1',[sid]).catch(()=>{})}db.release();await pool.end();console.log('G34_SYNTHETIC_FIXTURES_CLEANED')}}
main().catch(e=>{console.error('G34_GATE_FAILED',e.stack||e.message);process.exitCode=1})
