require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const { pool }=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http')
const crypto=require('node:crypto')
const PORT=Number(process.env.TEST_API_PORT||5018)
function req(pathname,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+pathname,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await req('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g15${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G10 QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role};users[key].cookie=await login(email,password,role,code)}
let r=await req('/portal/paper-studio/publisher-review/academic-publication-precheck','POST',{},users.teacher.cookie);if(r.status!==403)throw Error(`teacher precheck leaked ${r.status}`);console.log('PASS teacher cannot access academic publication precheck')
r=await req('/portal/paper-studio/publisher-review/academic-publication-precheck','POST',{},users.admin.cookie);if(r.status!==200||r.json.data?.valid!==false||!r.json.data?.issues?.includes('editionEvidence:STATUS_NOT_INDEPENDENTLY_APPROVED')||!r.json.data?.issues?.includes('BIO9-C1-THEORY-LAW-001:DECISION_MISSING')||!r.json.data?.issues?.includes('signedPublication:STATUS_NOT_PUBLISHED_APPROVED')||r.json.policy?.persisted!==false||r.json.policy?.academicApprovalChanged!==false||r.json.policy?.publisherApprovalChanged!==false||r.json.policy?.canonicalWriteChanged!==false)throw Error(`current academic precheck contract failed ${JSON.stringify(r.json)}`);console.log('PASS current academic/publication state fails closed without mutation')
console.log('V6G15_ACADEMIC_HTTP 2/2 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G15_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G15_FAIL',e.stack||e.message);process.exit(1)})
