const test=require('node:test')
const assert=require('node:assert/strict')
const {buildPublisherApprovalActivationPreflight}=require('../services/papers/paperPublisherApprovalActivationPreflightV6G13')
const decision={valid:true,bindings:{envelopeSha256:'a'.repeat(64)}}
const evidence={valid:true,manifestSha:'b'.repeat(64),sourceCommit:'commit1',scope:{grade:9,subject:'Biology'},approvedQuestionCount:1,issues:[]}
function deps(overrides={}){return {validatePublisherApprovalDecision:()=>decision,verifyCurriculumPublisherEvidence:async()=>evidence,buildCanonicalCutoverReadiness:async()=>({ready:false,blockers:['CURRICULUM_PUBLISHER_NOT_PRODUCTION_APPROVED','CANONICAL_REGISTRY_WRITE_DISABLED']}),publisherProductionApproved:false,canonicalWriteEnabled:false,...overrides}}
test('eligible governed chain proposes only publisher approval flag change',async()=>{const r=await buildPublisherApprovalActivationPreflight({}, {}, {}, deps());assert.equal(r.valid,true);assert.deepEqual(r.proposedChange,{name:'PAPER_CURRICULUM_PUBLISHER_PRODUCTION_APPROVED',from:false,to:true});assert.equal(r.invariant.canonicalRegistryWriteEnabled,false);assert.equal(r.policy.envChanged,false);assert.equal(r.policy.publisherApprovalChanged,false);assert.equal(r.policy.canonicalWriteChanged,false)})
test('incomplete publisher evidence blocks activation',async()=>{await assert.rejects(()=>buildPublisherApprovalActivationPreflight({}, {}, {}, deps({verifyCurriculumPublisherEvidence:async()=>({valid:false,issues:['X']})})),e=>e.code==='PUBLISHER_EVIDENCE_NOT_READY'&&e.status===409)})
test('canonical write already enabled blocks publisher activation',async()=>{await assert.rejects(()=>buildPublisherApprovalActivationPreflight({}, {}, {}, deps({canonicalWriteEnabled:true})),e=>e.code==='CANONICAL_WRITE_MUST_REMAIN_DISABLED')})
test('unexpected readiness blockers fail closed',async()=>{await assert.rejects(()=>buildPublisherApprovalActivationPreflight({}, {}, {}, deps({buildCanonicalCutoverReadiness:async()=>({ready:false,blockers:['CURRICULUM_PUBLISHER_NOT_PRODUCTION_APPROVED','CANONICAL_REGISTRY_WRITE_DISABLED','EXTRA_BLOCKER']})})),e=>e.code==='PRE_APPROVAL_READINESS_UNEXPECTED'&&e.issues.includes('EXTRA_BLOCKER'))})
test('already-enabled publisher approval is not reactivated',async()=>{await assert.rejects(()=>buildPublisherApprovalActivationPreflight({}, {}, {}, deps({publisherProductionApproved:true})),e=>e.code==='PUBLISHER_APPROVAL_ALREADY_ENABLED')})
