require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http')
const crypto=require('node:crypto')
const PORT=Number(process.env.TEST_API_PORT||5018),BASE='/api'
const request=(url,method='GET',body=null,cookie='')=>new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const req=http.request({hostname:'127.0.0.1',port:PORT,path:BASE+url,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:8000},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{let json={};try{json=JSON.parse(out)}catch{}resolve({status:res.statusCode,json,headers:res.headers})})});req.on('error',reject);if(raw)req.write(raw);req.end()})
async function login(actor,password,code){return new Promise((resolve,reject)=>{const raw=JSON.stringify({email:actor.email,password,role:actor.role,school_code:code});const req=http.request({hostname:'127.0.0.1',port:PORT,path:'/api/auth/login',method:'POST',headers:{Host:'api.assps.edu.pk','Content-Type':'application/json','Content-Length':Buffer.byteLength(raw)}},res=>{res.resume();res.on('end',()=>resolve((res.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')))});req.on('error',reject);req.end(raw)})}
async function main(){const db=await pool.connect();let sid;try{
 const suf=crypto.randomBytes(5).toString('hex'),code='v6edelivery'+suf,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10)
 sid=(await db.query("INSERT INTO schools(name,code,status,tenant_id) VALUES('Synthetic V6E Delivery QA',$1,'active',$1) RETURNING id",[code])).rows[0].id
 const actors={};for(const [key,role] of [['teacherA','teacher'],['teacherB','teacher'],['admin','admin']]){const email=`${key}-${suf}@invalid.example`;const u=(await db.query('INSERT INTO users(school_id,tenant_id,name,email,role,password,is_active) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING id',[sid,code,key,email,role,hash])).rows[0];actors[key]={id:u.id,email,role};actors[key].cookie=await login(actors[key],password,code)}
 await db.query("INSERT INTO teacher_class_assignments(school_id,teacher_user_id,class_name,section,subject,is_active) VALUES($1,$2,'Seven','A','Science',true),($1,$3,'Eight','B','Math',true)",[sid,actors.teacherA.id,actors.teacherB.id])
 const paper={name:'V6E Science Delivery',creationMethod:'blank',userAuthored:true,documentFormat:'pts-native-v13',config:{classLevel:'Seven',section:'A',subject:'Science',language:'dual'},numberedQuestionTypes:[{value:'mcq',questionNo:1,label:'MCQs',marks:1},{value:'short',questionNo:2,label:'Shorts',marks:2}],mcq_marks:1,short_marks:2,mcq:[{id:'m1',en:'First?',ur:'پہلا؟',answer:'B',options:[{id:'A',text:'a'},{id:'B',text:'b'}]},{id:'m2',en:'Second?',ur:'دوسرا؟',answer:'A',options:[{id:'A',text:'1'},{id:'B',text:'2'}]}],short:[{id:'s1',en:'Explain?',ur:'وضاحت؟',answerLines:3,answer:'Because'}],unknown:{preserve:true}}
 let r=await request('/paper/vault','POST',{paper},actors.teacherA.cookie);if(r.status!==201)throw Error('paper create failed '+r.status);const id=String(r.json.paper.id)
 r=await request(`/portal/paper-studio/papers/${id}/document-review`,'GET',null,actors.teacherA.cookie);if(r.status!==200)throw Error('review failed');const rev1Hash=r.json.review.snapshotHash
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:1,snapshotHash:rev1Hash},actors.teacherA.cookie)
 if(r.status!==200)throw Error('manifest current failed '+JSON.stringify(r.json));const m1=r.json.data
 if(m1.paperId!==id||m1.revision!==1||!m1.isCurrent||m1.architectureVersion!=='v6-e2'||m1.nativePresentation?.renderPolicy!=='SOURCE_NATIVE_RENDER_ONLY'||!String(m1.nativePresentation?.renderer||'').includes('PTSPaperGenerator')||m1.nativePresentation?.cutoverReady!==false||m1.channels.print.state!=='blocked'||m1.channels.print.reason!=='SOURCE_NATIVE_RENDER_GOLDEN_APPROVAL_PENDING')throw Error('revision binding/native renderer gate wrong')
 if(!m1.channels.onlineTest.content.contentEligible||m1.channels.onlineTest.content.totalQuestions!==3||m1.channels.onlineTest.content.autoGradableQuestions!==2||m1.channels.onlineTest.content.manualReviewQuestions!==1||m1.channels.onlineTest.reason!=='ONLINE_TEST_PUBLISH_ADAPTER_PENDING')throw Error('online eligibility wrong '+JSON.stringify(m1.channels.onlineTest))
 if(m1.canonicalWriteAllowed||m1.printApprovalClaim||m1.publishApprovalClaim)throw Error('false authority granted')
 console.log('PASS current immutable revision manifest + honest print/publish gates')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:1,snapshotHash:'f'.repeat(64)},actors.teacherA.cookie);if(r.status!==409||r.json.code!=='DELIVERY_SOURCE_MISMATCH')throw Error('wrong hash not blocked');console.log('PASS wrong snapshot hash rejected')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:1,snapshotHash:rev1Hash},actors.teacherB.cookie);if(r.status!==404)throw Error('cross-owner manifest leaked '+r.status);console.log('PASS cross-teacher delivery source is non-leaking 404')
 const {legacyPaperToWorkingDocument}=await import('file:///root/workspace/apex-release/saas-src/al-siddique-backend/src/services/papers/saasReviewedContract/losslessLegacyBridgeV6D.mjs')
 const working=legacyPaperToWorkingDocument(paper),edited=structuredClone(working);edited.blocks[1].contentHtml='<p>Second revision?</p>'
 r=await request(`/portal/paper-studio/papers/${id}`,'PATCH',{workingDocument:edited,expectedRevision:1,expectedSnapshotHash:rev1Hash},actors.teacherA.cookie);if(r.status!==200||r.json.data.revision!==2)throw Error('guarded edit failed '+JSON.stringify(r.json));const rev2Hash=r.json.data.snapshotHash
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:1,snapshotHash:rev1Hash},actors.teacherA.cookie);if(r.status!==200||r.json.data.isCurrent||r.json.data.channels.onlineTest.reason!=='CURRENT_REVISION_REQUIRED')throw Error('historical manifest current-only gate failed');console.log('PASS historical revision remains inspectable but cannot be online-published as current')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:2,snapshotHash:rev2Hash},actors.teacherA.cookie);if(r.status!==200||!r.json.data.isCurrent||r.json.data.revision!==2)throw Error('rev2 manifest failed');if(r.json.data.deliveryKey===m1.deliveryKey)throw Error('delivery key did not bind revision');console.log('PASS delivery key changes with immutable revision')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:2,snapshotHash:rev2Hash},actors.admin.cookie);if(r.status!==200)throw Error('admin governed manifest failed');console.log('PASS admin can create governed revision manifest')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{snapshotHash:rev2Hash},actors.teacherA.cookie);if(r.status!==400||r.json.code!=='REVISION_REQUIRED')throw Error('missing revision accepted')
 r=await request(`/portal/paper-studio/papers/${id}/delivery-manifest`,'POST',{revision:2},actors.teacherA.cookie);if(r.status!==400||r.json.code!=='SNAPSHOT_HASH_REQUIRED')throw Error('missing hash accepted');console.log('PASS revision and hash are both mandatory')
 const unsupported={name:'Unsupported Diagram',config:{classLevel:'Seven',section:'A',subject:'Science'},numberedQuestionTypes:[{value:'diagram',questionNo:1,label:'Diagram',marks:5}],diagram_marks:5,diagram:[{id:'d1',en:'Draw a labelled cell',ur:'خلیہ بنائیں'}]}
 r=await request('/paper/vault','POST',{paper:unsupported},actors.teacherA.cookie);if(r.status!==201)throw Error('unsupported fixture save failed');const uid=String(r.json.paper.id)
 r=await request(`/portal/paper-studio/papers/${uid}/document-review`,'GET',null,actors.teacherA.cookie);const uh=r.json.review.snapshotHash
 r=await request(`/portal/paper-studio/papers/${uid}/delivery-manifest`,'POST',{revision:1,snapshotHash:uh},actors.teacherA.cookie);if(r.status!==200||r.json.data.channels.onlineTest.content.contentEligible||r.json.data.channels.onlineTest.reason!=='UNSUPPORTED_QUESTION_TYPES'||r.json.data.channels.onlineTest.content.unsupportedTypes[0]?.kind!=='diagram')throw Error('unsupported online type not blocked')
 console.log('PASS unsupported online question type reported and blocked')
 console.log('V6E_DELIVERY_MANIFEST_GATE 8/8 PASS')
}finally{if(sid){await db.query('DELETE FROM paper_vault WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM teacher_class_assignments WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM users WHERE school_id=$1',[sid]).catch(()=>{});await db.query('DELETE FROM schools WHERE id=$1',[sid]).catch(()=>{})}db.release();await pool.end();console.log('V6E_SYNTHETIC_FIXTURES_CLEANED')}}
main().catch(e=>{console.error('V6E_GATE_FAILED',e.stack||e.message);process.exitCode=1})
