const test=require('node:test')
const assert=require('node:assert/strict')
const {buildPublisherReleaseEnvelope}=require('../services/papers/paperPublisherReleaseEnvelopeV6G17')
function deps({academicValid=true}={}){return{
  buildPublisherPromotionEnvelope:()=>({valid:true,envelopeSha256:'1'.repeat(64),envelope:{publisherEvidenceSha256:'2'.repeat(64),publisherSourceCommit:'abc123'}}),
  validatePublisherKeyCustodyPreflight:()=>({valid:true,publicKey:{type:'Ed25519',fingerprintSha256:'3'.repeat(64)},custody:{evidenceId:'custody-1',reviewerId:71,reviewDate:'2026-10-06T10:00:00Z',reviewedArtifactSha256:'4'.repeat(64),privateKeyCustodyMode:'EXTERNAL_HSM'}}),
  buildAcademicPublicationPrecheck:()=>academicValid?{valid:true,editionReview:{editionEvidence:{englishPdfSha256:'5'.repeat(64),urduPdfSha256:'6'.repeat(64)}},pinnedConflictBase:{sha256:'7'.repeat(64),issueIds:['BIO9-C1-THEORY-LAW-001','BIO9-C1-MALARIA-CHRONOLOGY-002']},approvedQuestionBinding:{sourceRef:'EN-BIO9-C1-A-Q01',medium:'English',verifiedPhysicalPage:22,sourcePdfSha256:'5'.repeat(64)},publication:{recordsDigest:'8'.repeat(64),recordCount:1},issues:[]}:{valid:false,issues:['REAL_ACADEMIC_REVIEW_REQUIRED']}
}}
test('G17 deterministically binds G10 G14 and G16 into one release envelope',()=>{const a=buildPublisherReleaseEnvelope({},deps()),b=buildPublisherReleaseEnvelope({},deps());assert.equal(a.valid,true);assert.equal(a.envelopeSha256,b.envelopeSha256);assert.equal(a.envelope.promotionEnvelopeSha256,'1'.repeat(64));assert.equal(a.envelope.publisherPublicKey.fingerprintSha256,'3'.repeat(64));assert.equal(a.envelope.publication.recordsDigest,'8'.repeat(64));assert.equal(a.envelope.policy.signatureCreated,false);assert.equal(a.envelope.policy.publisherApprovalChanged,false);assert.equal(a.envelope.policy.canonicalWriteChanged,false)})
test('G17 fails closed when academic/publication precheck is incomplete',()=>{assert.throws(()=>buildPublisherReleaseEnvelope({},deps({academicValid:false})),e=>e.status===409&&e.code==='ACADEMIC_PUBLICATION_PRECHECK_BLOCKED'&&e.issues.includes('REAL_ACADEMIC_REVIEW_REQUIRED'))})
test('G17 never accepts or creates private-key state',()=>{const r=buildPublisherReleaseEnvelope({},deps());assert.equal(r.envelope.policy.privateKeyAccepted,false);assert.equal(r.envelope.policy.privateKeyAccessed,false);assert.equal(r.envelope.policy.persisted,false);assert.match(r.nextAction,/REAL_EXTERNAL_SIGNATURE/)})
