require('dotenv').config({path:'/var/www/apex-backend/.env'});
const {pool}=require('../config/database');const bcrypt=require('bcryptjs');const http=require('node:http');const crypto=require('node:crypto');
const PORT=Number(process.env.TEST_API_PORT || 5000);
function request(path,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const req=http.request({host:'127.0.0.1',port:PORT,path:'/api'+path,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>{let json={};try{json=JSON.parse(text)}catch{}resolve({status:res.statusCode,json,headers:res.headers})})});req.on('error',reject);if(raw)req.write(raw);req.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${email} ${r.status}`);return (r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`vaultqa${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic Paper Vault QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const role of ['admin','teacher','teacher']){const key=role==='admin'?'admin':Object.keys(users).includes('teacherA')?'teacherB':'teacherA';const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role}}
await c.query("insert into teacher_class_assignments(school_id,teacher_user_id,class_name,section,subject,is_active) values($1,$2,'Seven','','Science',true),($1,$3,'Eight','','Math',true)",[sid,users.teacherA.id,users.teacherB.id]);
for(const u of Object.values(users))u.cookie=await login(u.email,password,u.role,code);
const paperA={name:'Teacher A Science Draft',config:{classLevel:'Seven',subject:'Science',totalMarks:50},selectedMCQ:[]};
let r=await request('/paper/vault','POST',{paper:paperA},users.teacherA.cookie);if(r.status!==201||!r.json?.paper?.id)throw Error(`teacherA save ${r.status} ${JSON.stringify(r.json)}`);const idA=r.json.paper.id;console.log('PASS teacher A saves assigned class',idA);
r=await request('/paper/vault','POST',{paper:{name:'Wrong class',config:{classLevel:'Eight',subject:'Science'}}},users.teacherA.cookie);if(r.status!==403)throw Error(`unassigned class expected403 got${r.status}`);console.log('PASS teacher unassigned class blocked 403');
r=await request('/paper/vault','GET',null,users.teacherA.cookie);if(r.status!==200||r.json.scope!=='mine'||r.json.papers.length!==1||String(r.json.papers[0].id)!==String(idA))throw Error('teacherA list scope failed');console.log('PASS teacher A sees only own vault');
r=await request('/paper/vault','GET',null,users.teacherB.cookie);if(r.status!==200||r.json.papers.length!==0)throw Error(`teacherB saw foreign papers ${JSON.stringify(r.json)}`);console.log('PASS teacher B cannot list teacher A paper');
r=await request(`/paper/vault/${idA}`,'PATCH',{name:'Teacher B attack'},users.teacherB.cookie);if(r.status!==404)throw Error(`teacherB patch expected404 got${r.status}`);console.log('PASS teacher B cannot edit teacher A paper');
r=await request('/paper/vault','POST',{paper:{name:'Teacher B Math Draft',config:{classLevel:'Eight',subject:'Math'}}},users.teacherB.cookie);if(r.status!==201)throw Error(`teacherB save ${r.status}`);const idB=r.json.paper.id;
r=await request('/paper/vault','GET',null,users.admin.cookie);if(r.status!==200||r.json.scope!=='school'||r.json.papers.length!==2)throw Error(`admin school list failed ${JSON.stringify(r.json)}`);console.log('PASS admin sees school-wide two-paper library');
r=await request(`/paper/vault/${idA}`,'PATCH',{name:'missing precondition'},users.teacherA.cookie);if(r.status!==428||r.json.code!=='EXPECTED_REVISION_REQUIRED')throw Error(`missing PATCH revision expected428 got${r.status}`);console.log('PASS legacy PATCH requires expectedRevision 428');
r=await request(`/paper/vault/${idA}`,'PATCH',{name:'A renamed',expectedRevision:1},users.teacherA.cookie);if(r.status!==200||r.json.paper.revision!==2)throw Error(`teacherA revision update failed ${r.status}`);console.log('PASS owner rename increments revision');
r=await request(`/paper/vault/${idA}`,'PATCH',{name:'stale',expectedRevision:1},users.teacherA.cookie);if(r.status!==409||r.json.code!=='REVISION_CONFLICT')throw Error(`stale revision expected409 got${r.status}`);console.log('PASS optimistic concurrency conflict 409');
r=await request(`/paper/vault/${idA}`,'DELETE',null,users.teacherA.cookie);if(r.status!==428||r.json.code!=='EXPECTED_REVISION_REQUIRED')throw Error(`missing DELETE revision expected428 got${r.status}`);console.log('PASS legacy DELETE requires expectedRevision 428');
r=await request(`/paper/vault/${idA}`,'DELETE',{expectedRevision:1},users.teacherA.cookie);if(r.status!==409||r.json.code!=='REVISION_CONFLICT')throw Error(`stale delete expected409 got${r.status}`);console.log('PASS stale delete blocked 409');
r=await request(`/paper/vault/${idA}`,'DELETE',{expectedRevision:2},users.teacherA.cookie);if(r.status!==200)throw Error('owner delete failed');r=await request('/paper/vault','GET',null,users.teacherA.cookie);if(r.json.papers.length!==0)throw Error('deleted paper visible');console.log('PASS soft delete removes owner paper at current revision');
console.log('PAPER_VAULT_ISOLATION 11/11 PASS');
}finally{if(sid){await c.query('delete from paper_vault where school_id=$1',[sid]).catch(()=>{});await c.query('delete from teacher_class_assignments where school_id=$1',[sid]).catch(()=>{});await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{});}c.release();await pool.end();console.log('SYNTHETIC_VAULT_FIXTURES_CLEANED')}})().catch(e=>{console.error('FAIL',e.stack||e.message);process.exit(1)});
