const test=require('node:test')
const assert=require('node:assert/strict')
const {validatePublisherApprovalDecision}=require('../services/papers/paperPublisherApprovalDecisionV6G12')
const signature={valid:true,envelopeSha256:'a'.repeat(64),detachedSignatureSha256:'b'.repeat(64),publicKeyFingerprintSha256:'c'.repeat(64)}
const verify=()=>signature
function approval(){return{status:'GOVERNED_PRODUCTION_APPROVAL',decision:'APPROVE_FOR_PRODUCTION',approvalId:'approval-bio9-001',approverUserId:7001,approvedAt:'2026-10-06T10:00:00Z',scope:{grade:9,subject:'Biology'},envelopeSha256:signature.envelopeSha256,detachedSignatureSha256:signature.detachedSignatureSha256,publisherPublicKeyFingerprintSha256:signature.publicKeyFingerprintSha256,rationale:'Independent governed publisher approval after evidence review.',releaseTicketId:'release-bio9-001'}}
test('properly bound governed approval validates without changing flags',()=>{const r=validatePublisherApprovalDecision({}, {}, approval(),{verifyPublisherDetachedSignature:verify,forbidApproverIds:[1]});assert.equal(r.valid,true);assert.equal(r.policy.approvalFlagChanged,false);assert.equal(r.policy.canonicalWriteChanged,false);assert.equal(r.nextAction,'EXPLICIT_PRODUCTION_APPROVAL_FLAG_CHANGE_REVIEW_REQUIRED')})
test('wrong envelope/signature/key bindings fail closed',()=>{const a=approval();a.envelopeSha256='d'.repeat(64);a.detachedSignatureSha256='e'.repeat(64);a.publisherPublicKeyFingerprintSha256='f'.repeat(64);assert.throws(()=>validatePublisherApprovalDecision({}, {}, a,{verifyPublisherDetachedSignature:verify}),e=>e.code==='PUBLISHER_APPROVAL_DECISION_INVALID'&&e.issues.includes('ENVELOPE_SHA_MISMATCH')&&e.issues.includes('DETACHED_SIGNATURE_SHA_MISMATCH')&&e.issues.includes('PUBLISHER_PUBLIC_KEY_FINGERPRINT_MISMATCH'))})
test('self approver id is rejected when forbidden',()=>{const a=approval();assert.throws(()=>validatePublisherApprovalDecision({}, {}, a,{verifyPublisherDetachedSignature:verify,forbidApproverIds:[7001]}),e=>e.issues.includes('APPROVER_NOT_INDEPENDENT'))})
test('invalid status and decision cannot pass as approval',()=>{const a=approval();a.status='PENDING';a.decision='REVIEW';assert.throws(()=>validatePublisherApprovalDecision({}, {}, a,{verifyPublisherDetachedSignature:verify}),e=>e.issues.includes('STATUS_NOT_GOVERNED_PRODUCTION_APPROVAL')&&e.issues.includes('DECISION_NOT_APPROVE_FOR_PRODUCTION'))})
