require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const {pool}=require('/var/www/apex-backend/config/database')
const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs')
const http=require('node:http'); const crypto=require('node:crypto'); const fs=require('node:fs'); const path=require('node:path')
const {REVIEW_NAMES}=require('../services/papers/paperIndependentReviewIntakeV6G4')
const PORT=Number(process.env.TEST_API_PORT||5018)
function request(pathname,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+pathname,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return(r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
function currentReviewBundle(reviewerBase){const pubPath=process.env.PAPER_CURRICULUM_PUBLISHER_EVIDENCE_PATH;const pub=JSON.parse(fs.readFileSync(pubPath,'utf8'));const draft=JSON.parse(fs.readFileSync(path.join(path.dirname(pubPath),pub.artifacts.operationalReviewEvidenceDraft.file),'utf8'));const manifests=draft.reviewArtifactManifests||{};const operationalReviews={};for(const [i,name] of REVIEW_NAMES.entries())operationalReviews[name]={status:'INDEPENDENTLY_APPROVED',evidenceId:`ev-${name}`,reviewerId:reviewerBase+i,reviewedArtifactSha256:manifests[name]?.sha256||'f'.repeat(64),reviewDate:'2026-10-06T10:00:00Z',scope:{grade:9,subject:'Biology'},result:'APPROVED',rationale:'Independent reviewer checked the exact sealed evidence artifact.'};return{operationalReviews}}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g12${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G12 QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role};users[key].cookie=await login(email,password,role,code)}
let r=await request('/portal/paper-studio/publisher-review/approval-activation-precheck','POST',{},users.teacher.cookie);if(r.status!==403)throw Error(`teacher approval activation leaked ${r.status}`);console.log('PASS teacher cannot access publisher approval activation precheck')
r=await request('/portal/paper-studio/publisher-review/approval-activation-precheck','POST',{reviewBundle:currentReviewBundle(users.admin.id+1000000),signature:{signatureBase64:'AA==',publicKeyFingerprintSha256:'f'.repeat(64),envelopeSha256:'e'.repeat(64)},approval:{status:'GOVERNED_PRODUCTION_APPROVAL',decision:'APPROVE_FOR_PRODUCTION'}},users.admin.cookie);if(r.status!==409||r.json.code!=='PUBLISHER_PROMOTION_PRECHECK_BLOCKED'||!r.json.issues?.includes('signedPublisherKeyCustody:SEALED_REVIEW_ARTIFACT_NOT_AVAILABLE'))throw Error(`current pack did not stop before approval activation ${JSON.stringify(r.json)}`);console.log('PASS current pack cannot reach approval activation before external evidence chain is complete')
console.log('V6G13_ACTIVATION_HTTP 2/2 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G13_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G13_FAIL',e.stack||e.message);process.exit(1)})
