require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'})
const { pool } = require('/var/www/apex-backend/config/database')
const bcrypt = require('/var/www/apex-backend/node_modules/bcryptjs')
const http = require('node:http')
const crypto = require('node:crypto')
const { REVIEW_NAMES } = require('../services/papers/paperIndependentReviewIntakeV6G4')
const PORT = Number(process.env.TEST_API_PORT || 5018)
function request(path,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const req=http.request({host:'127.0.0.1',port:PORT,path:'/api'+path,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>{let json={};try{json=JSON.parse(text)}catch{}resolve({status:res.statusCode,json,headers:res.headers})})});req.on('error',reject);if(raw)req.write(raw);req.end()})}
async function login(email,password,role,code){const r=await request('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return (r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
function completeBundle(reviewerId){const operationalReviews={};for(const name of REVIEW_NAMES)operationalReviews[name]={status:'INDEPENDENTLY_APPROVED',evidenceId:`ev-${name}`,reviewerId,reviewedArtifactSha256:'a'.repeat(64),reviewDate:'2026-10-06T10:00:00Z',scope:{grade:9,subject:'Biology'},result:'APPROVED',rationale:'Independent reviewer inspected the exact sealed technical evidence.'};return {operationalReviews}}
;(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`g8${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic G8 Review QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const [key,role] of [['admin','admin'],['teacher','teacher']]){const email=`${key}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,key,email,role,hash])).rows[0].id;users[key]={id,email,role};users[key].cookie=await login(email,password,role,code)}
let r=await request('/portal/paper-studio/publisher-review/validate','POST',{},users.teacher.cookie);if(r.status!==403)throw Error(`teacher reviewer validation leaked ${r.status}`);console.log('PASS teacher cannot access independent review validator')
r=await request('/portal/paper-studio/publisher-review/validate','POST',{},users.admin.cookie);if(r.status!==200||r.json.data?.valid!==false||r.json.policy?.persisted!==false||r.json.policy?.approvalChanged!==false||r.json.policy?.canonicalWriteChanged!==false)throw Error(`admin draft validation contract failed ${JSON.stringify(r.json)}`);console.log('PASS admin can validate draft without persistence or approval mutation')
r=await request('/portal/paper-studio/publisher-review/validate','POST',completeBundle(users.admin.id),users.admin.cookie);if(r.status!==200||r.json.data?.valid!==false||!r.json.data?.issues?.some(x=>x.endsWith(':REVIEWER_NOT_INDEPENDENT')))throw Error(`self-review was not rejected ${JSON.stringify(r.json)}`);console.log('PASS caller cannot self-approve independent review records')
r=await request('/portal/paper-studio/publisher-review/validate','POST',completeBundle(users.admin.id+1000000),users.admin.cookie);if(r.status!==200||r.json.data?.valid!==true||r.json.policy?.persisted!==false)throw Error(`complete external review bundle did not validate ${JSON.stringify(r.json)}`);console.log('PASS structurally complete external review bundle validates read-only')
console.log('V6G8_REVIEW_HTTP 4/4 PASS')
}finally{if(sid){await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{})}c.release();await pool.end();console.log('V6G8_SYNTHETIC_FIXTURES_CLEANED')}})().catch(e=>{console.error('V6G8_FAIL',e.stack||e.message);process.exit(1)})
