const test=require('node:test')
const assert=require('node:assert/strict')
const crypto=require('node:crypto')
const {validatePublisherKeyCustodyPreflight,fingerprint}=require('../services/papers/paperPublisherKeyCustodyPreflightV6G14')
function fixture(){const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const publicKeyPem=publicKey.export({type:'spki',format:'pem'}).toString();const privateKeyPem=privateKey.export({type:'pkcs8',format:'pem'}).toString();const fp=fingerprint(publicKey);const record={status:'INDEPENDENTLY_APPROVED',evidenceId:'key-custody-20261006',reviewerId:9001,reviewDate:'2026-10-06T10:00:00Z',scope:{grade:9,subject:'Biology'},keyType:'Ed25519',publicKeyFingerprintSha256:fp,privateKeyCustodyMode:'EXTERNAL_OFFLINE',privateKeyStoredOnApplicationServer:false,rotationProcedureApproved:true,revocationProcedureApproved:true,reviewedArtifactSha256:'a'.repeat(64),rationale:'Independent reviewer verified offline publisher key custody controls.'};return{publicKeyPem,privateKeyPem,record,fp}}
test('valid public key and independent offline custody evidence passes read-only',()=>{const f=fixture();const r=validatePublisherKeyCustodyPreflight(f.publicKeyPem,f.record,{forbidReviewerIds:[1]});assert.equal(r.valid,true);assert.equal(r.publicKey.fingerprintSha256,f.fp);assert.equal(r.policy.publicKeyPersisted,false);assert.equal(r.policy.privateKeyAccepted,false);assert.equal(r.policy.envChanged,false);assert.equal(r.policy.publisherApprovalChanged,false);assert.equal(r.policy.canonicalWriteChanged,false)})
test('private key material is always rejected',()=>{const f=fixture();assert.throws(()=>validatePublisherKeyCustodyPreflight(f.privateKeyPem,f.record),e=>e.code==='PRIVATE_KEY_MATERIAL_FORBIDDEN'&&e.status===400)})
test('wrong public key fingerprint fails closed',()=>{const f=fixture();f.record.publicKeyFingerprintSha256='f'.repeat(64);assert.throws(()=>validatePublisherKeyCustodyPreflight(f.publicKeyPem,f.record),e=>e.code==='PUBLISHER_KEY_CUSTODY_INVALID'&&e.issues.includes('PUBLIC_KEY_FINGERPRINT_MISMATCH'))})
test('self reviewer id is rejected',()=>{const f=fixture();assert.throws(()=>validatePublisherKeyCustodyPreflight(f.publicKeyPem,f.record,{forbidReviewerIds:[9001]}),e=>e.code==='PUBLISHER_KEY_CUSTODY_INVALID'&&e.issues.includes('REVIEWER_NOT_INDEPENDENT'))})
