const test=require('node:test')
const assert=require('node:assert/strict')
const {buildHumanAuthorityBoundary,classifyPublisherIssue}=require('../services/papers/paperHumanAuthorityBoundaryV6G18')
const baseGates={canonicalRegistryPresent:true,canonicalRuntimeRoleApproved:true,canonicalWriteDefenseApproved:true,canonicalPayloadContractApproved:true,canonicalRendererParityApproved:true,canonicalRendererEvidenceVerified:true,backupRestoreDrillApproved:true,tenantRlsApproved:true,canonicalRegistryWriteEnabled:false,curriculumPublisherProductionApproved:false}
const deps=(over={})=>({
 buildCanonicalCutoverReadiness:async()=>({ready:false,gates:{...baseGates,...(over.gates||{})},blockers:over.blockers||['CURRICULUM_PUBLISHER_EVIDENCE_INVALID','CURRICULUM_PUBLISHER_NOT_PRODUCTION_APPROVED','CANONICAL_REGISTRY_WRITE_DISABLED']}),
 verifyCurriculumPublisherEvidence:async()=>({valid:false,manifestSha:'a'.repeat(64),sourceCommit:'b'.repeat(40),approvedQuestionCount:0,issues:over.issues||['preflight:NO_APPROVED_LIVE_ACADEMIC_RECORDS','preflight:GENUINE_SIGNED_CURRICULUM_PUBLICATION_MISSING','publisher evidence has no independently approved questions','publisher release state incomplete: academicSignoffComplete','publisher evidence still declares open issues']})
})
test('G18 marks boundary only when technical gates are green and remaining work is human authority',async()=>{const r=await buildHumanAuthorityBoundary(deps());assert.equal(r.valid,true);assert.equal(r.boundaryReached,true);assert.equal(r.technicalReady,true);assert.deepEqual(r.technicalFailures,[]);assert.deepEqual(r.unknownPublisherIssues,[]);assert.ok(r.humanAuthorityBlockers.length>=4);assert.ok(r.deliberateSafetyLocks.includes('CANONICAL_REGISTRY_WRITE_DISABLED'));assert.equal(r.policy.canonicalWriteChanged,false);assert.equal(r.policy.approvalChanged,false)})
test('G18 fails closed when a technical gate regresses',async()=>{const r=await buildHumanAuthorityBoundary(deps({gates:{canonicalRendererEvidenceVerified:false}}));assert.equal(r.valid,false);assert.equal(r.technicalReady,false);assert.ok(r.technicalFailures.includes('canonicalRendererEvidenceVerified'));assert.match(r.nextAction,/TECHNICAL/)})
test('G18 fails closed on unknown publisher issue instead of calling it human-only',async()=>{const r=await buildHumanAuthorityBoundary(deps({issues:['unexpected cryptographic drift']}));assert.equal(r.valid,false);assert.deepEqual(r.unknownPublisherIssues,['unexpected cryptographic drift'])})
test('G18 classifier recognizes independent review blockers but not arbitrary failures',()=>{assert.equal(classifyPublisherIssue('preflight:UR_CHAPTER_INDEX_PENDING'),'HUMAN_AUTHORITY_REQUIRED');assert.equal(classifyPublisherIssue('publisher release state incomplete: publisherKeyCustodyApproved'),'HUMAN_AUTHORITY_REQUIRED');assert.equal(classifyPublisherIssue('database unavailable'),'UNKNOWN')})
