require('/var/www/apex-backend/node_modules/dotenv').config({path:'/var/www/apex-backend/.env'});
const {pool}=require('/var/www/apex-backend/config/database');const bcrypt=require('/var/www/apex-backend/node_modules/bcryptjs');const http=require('node:http');const crypto=require('node:crypto');
const PORT=Number(process.env.TEST_API_PORT || 5000);function req(path,method='GET',body=null,cookie=''){return new Promise((resolve,reject)=>{const raw=body?JSON.stringify(body):null;const q=http.request({host:'127.0.0.1',port:PORT,path:'/api'+path,method,headers:{Host:'api.assps.edu.pk','Content-Type':'application/json',...(raw?{'Content-Length':Buffer.byteLength(raw)}:{}),...(cookie?{Cookie:cookie}:{})},timeout:7000},r=>{let t='';r.on('data',c=>t+=c);r.on('end',()=>{let j={};try{j=JSON.parse(t)}catch{}resolve({status:r.statusCode,json:j,headers:r.headers})})});q.on('error',reject);if(raw)q.write(raw);q.end()})}
async function login(email,password,role,code){const r=await req('/auth/login','POST',{email,password,role,school_code:code});if(r.status!==200)throw Error(`login ${role} ${r.status}`);return (r.headers['set-cookie']||[]).map(x=>x.split(';')[0]).join('; ')}
(async()=>{const c=await pool.connect();let sid;try{const suf=crypto.randomBytes(5).toString('hex'),code=`qbqa${suf}`,password=crypto.randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,10);sid=(await c.query("insert into schools(name,code,status,tenant_id) values('Synthetic QBank QA',$1,'active',$1) returning id",[code])).rows[0].id;const users={};for(const spec of [['admin','admin'],['teacherA','teacher'],['teacherB','teacher']]){const email=`${spec[0]}-${suf}@invalid.example`;const id=(await c.query('insert into users(school_id,tenant_id,name,email,role,password,is_active) values($1,$2,$3,$4,$5,$6,true) returning id',[sid,code,spec[0],email,spec[1],hash])).rows[0].id;users[spec[0]]={id,email,role:spec[1]}}await c.query("insert into teacher_class_assignments(school_id,teacher_user_id,class_name,section,subject,is_active) values($1,$2,'Seven','','Science',true),($1,$3,'Eight','','Math',true)",[sid,users.teacherA.id,users.teacherB.id]);for(const u of Object.values(users))u.cookie=await login(u.email,password,u.role,code);
const make=(cls,subject,text)=>({class_level:cls,subject,question_type:'short',question_text:text,marks:2,is_approved:true});let r=await req('/question-bank','POST',make('Seven','Science','Science QA '+suf),users.admin.cookie);if(r.status!==201)throw Error('admin add Science '+r.status+' '+JSON.stringify(r.json));const scienceId=r.json.data.id;r=await req('/question-bank','POST',make('Eight','Math','Math QA '+suf),users.admin.cookie);if(r.status!==201)throw Error('admin add Math '+r.status);const mathId=r.json.data.id;console.log('PASS admin creates approved school questions');
r=await req('/question-bank?limit=50', 'GET',null,users.teacherA.cookie);if(r.status!==200)throw Error('teacherA list '+r.status);const ids=(r.json.data||[]).map(x=>String(x.id));if(!ids.includes(String(scienceId))||ids.includes(String(mathId)))throw Error('teacherA scope leak '+JSON.stringify(ids));console.log('PASS teacher A sees assigned Science, not Math');
r=await req('/question-bank?approved=false&limit=50','GET',null,users.teacherA.cookie);if((r.json.data||[]).some(x=>!x.is_approved))throw Error('teacher forced unapproved visibility');console.log('PASS teacher cannot request unapproved questions');
r=await req('/question-bank','POST',make('Seven','Science','Teacher mutation'),users.teacherA.cookie);if(r.status!==403)throw Error('teacher POST expected403 got '+r.status);console.log('PASS teacher cannot add question');
r=await req(`/question-bank/${scienceId}`,'DELETE',null,users.teacherA.cookie);if(r.status!==403)throw Error('teacher DELETE expected403 got '+r.status);console.log('PASS teacher cannot delete question');
r=await req('/question-bank?limit=50','GET',null,users.admin.cookie);if(r.status!==200)throw Error('admin list '+r.status);const adminIds=(r.json.data||[]).map(x=>String(x.id));if(!adminIds.includes(String(scienceId))||!adminIds.includes(String(mathId)))throw Error('admin missing school questions');console.log('PASS admin retains school-wide Question Bank');console.log('QUESTION_BANK_SCOPE 6/6 PASS');
}finally{if(sid){await c.query('delete from question_bank where school_id=$1',[sid]).catch(()=>{});await c.query('delete from teacher_class_assignments where school_id=$1',[sid]).catch(()=>{});await c.query('delete from users where school_id=$1',[sid]).catch(()=>{});await c.query('delete from schools where id=$1',[sid]).catch(()=>{});}c.release();await pool.end();console.log('SYNTHETIC_QBANK_FIXTURES_CLEANED')}})().catch(e=>{console.error('FAIL',e.stack||e.message);process.exit(1)});
