const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')

test('governance tables are in strict FORCE-RLS migration path and failures are fatal',()=>{
 const rls=fs.readFileSync(path.join(__dirname,'../config/migrations/005_rls_policies.js'),'utf8')
 for(const table of ['question_masters','question_revisions','question_mappings','question_capture_requests']) assert.match(rls,new RegExp(`strictTables[^\\n]*${table}`))
 assert.match(rls,/ALTER TABLE \$\{table\} ENABLE ROW LEVEL SECURITY/)
 assert.match(rls,/ALTER TABLE \$\{table\} FORCE ROW LEVEL SECURITY/)
 assert.match(rls,/WITH CHECK/)
 const migrate=fs.readFileSync(path.join(__dirname,'../config/migrate.js'),'utf8')
 assert.ok(migrate.indexOf("007_question_bank_governance_v1") < migrate.indexOf("005_rls_policies"))
 assert.doesNotMatch(migrate,/Non-fatal, let the app start/)
 assert.match(migrate,/Security-critical authoring migration failed:[\s\S]*throw err/)
})
