'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const express=require('express')
const http=require('node:http')
const jwt=require('jsonwebtoken')
for(const [key,value] of Object.entries({
 DB_HOST:'127.0.0.1',DB_PORT:'55432',DB_NAME:'assps_core_signed_p7_20261008',
 DB_USER:'assps_core_test_login',DB_RUNTIME_ROLE:'apex_app_runtime',
 DB_ENFORCE_LEAST_PRIVILEGE_LOGIN:'true',
 DB_AUTH_USE_SIGNED_TENANT_CONTEXT:'true',
 JWT_SECRET:'isolated-synthetic-signing-key-only',
 DB_SIGNED_TENANT_RLS_ENABLED:'true',
 DB_SIGNED_TENANT_HMAC_KEY:process.env.CORE_SIGNED_TEST_KEY
})) assert.equal(process.env[key],value,'isolated gate '+key)
assert.match(process.env.CORE_SIGNED_TEST_KEY||'',/^[a-f0-9]{64}$/)
process.env.DB_STARTUP_PROBE='false'
const {pool,tenantContext,query}=require('../config/database')
const assessmentResultRoutes=require('../routes/assessmentResultRoutes')
const request=(port,path,token,method='GET',body=null)=>new Promise((resolve,reject)=>{
 const payload=body===null?null:JSON.stringify(body)
 const req=http.request({host:'127.0.0.1',port,path,method,headers:{
  ...(token?{Authorization:'Bearer '+token}:{}),
  ...(payload?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}:{})
 }},res=>{
  let raw='';res.on('data',c=>raw+=c)
  res.on('end',()=>{let json=null;try{json=JSON.parse(raw)}catch{};resolve({status:res.statusCode,json})})
 })
 req.on('error',reject)
 req.end(payload||undefined)
})
const ctx=(id,fn)=>tenantContext.run({rlsEnabled:true,isSuperAdmin:false,tenantId:id,actorId:999001},fn)
test('real Assessment Results HTTP router enforces teacher assignment role and tenant',async t=>{
 const schoolA=await ctx(900001,async()=> (await query("SELECT id,role,school_id,email FROM users WHERE email IN ('core-security-a@example.invalid','core-unassigned@example.invalid','core-admin@example.invalid','core-student@example.invalid') ORDER BY email")).rows)
 const teacherB=await ctx(900002,async()=> (await query("SELECT id,role,school_id,email FROM users WHERE email='core-security-b@example.invalid'")).rows[0])
 const byEmail=Object.fromEntries(schoolA.map(x=>[x.email,x]))
 const sign=(user,claims={})=>jwt.sign({...user,...claims},process.env.JWT_SECRET,{algorithm:'HS256',expiresIn:'3m'})
 const teacherA=sign(byEmail['core-security-a@example.invalid'])
 const unassigned=sign(byEmail['core-unassigned@example.invalid'])
 const adminA=sign(byEmail['core-admin@example.invalid'])
 const studentA=sign(byEmail['core-student@example.invalid'])
 const teacherBToken=sign(teacherB)
 const app=express()
 app.use(express.json())
 app.use((_req,_res,next)=>tenantContext.run({rlsEnabled:false,isSuperAdmin:false,tenantId:null},next))
 app.use('/api/assessment-results',assessmentResultRoutes)
 app.use('/api/attendance',require('../routes/attendanceRoutes'))
 app.use('/api/fees',require('../routes/feeRoutes'))
 app.use('/api/paper-studio',require('../routes/paperStudioRoutes'))
 const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s))})
 t.after(async()=>{await new Promise(r=>server.close(r));await pool.end()})
 const port=server.address().port
 let x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.result_id,'CORE-P6-RESULT-A')
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',unassigned)
 assert.equal(x.status,403,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',teacherBToken)
 assert.equal(x.status,404,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-B',teacherA)
 assert.equal(x.status,404,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',adminA)
 assert.equal(x.status,200,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',studentA)
 assert.equal(x.status,403,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A?school_id=900002',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.result_id,'CORE-P6-RESULT-A')
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',sign(byEmail['core-security-a@example.invalid'],{school_id:900002}))
 assert.equal(x.status,401,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',sign(byEmail['core-security-a@example.invalid'],{tenant_id:'synthetic-core-b'}))
 assert.equal(x.status,401,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',sign(byEmail['core-security-a@example.invalid'],{tenant_id:'synthetic-core-a'}))
 assert.equal(x.status,200,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',sign(byEmail['core-security-a@example.invalid'],{role:'super_admin'}))
 assert.equal(x.status,200,JSON.stringify(x))
 const branchA=sign({id:9900001,email:'phase6-branch-a@example.invalid',school_id:900001,tenant_id:'synthetic-core-a'})
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',branchA)
 assert.equal(x.status,200,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-B',branchA)
 assert.equal(x.status,404,JSON.stringify(x))
 const branchForgedSchool=sign({id:9900001,email:'phase6-branch-a@example.invalid',school_id:900002,tenant_id:'synthetic-core-b'})
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-B',branchForgedSchool)
 assert.equal(x.status,401,JSON.stringify(x))
 x=await request(port,'/api/assessment-results/CORE-P6-RESULT-A',null)
 assert.equal(x.status,401,JSON.stringify(x))
 // Production attendance router: assignment limits teacher to own class/school.
 x=await request(port,'/api/attendance?date=2026-10-08',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.count,1,JSON.stringify(x))
 assert.equal(x.json?.data?.[0]?.school_id,900001)
 x=await request(port,'/api/attendance?date=2026-10-08',unassigned)
 assert.equal(x.status,409,JSON.stringify(x))
 assert.equal(x.json?.code,"TEACHER_ASSIGNMENTS_REQUIRED")
 x=await request(port,'/api/attendance?date=2026-10-08&school_id=900002',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.count,1,JSON.stringify(x))
 x=await request(port,'/api/attendance?date=2026-10-08',adminA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.count,1,JSON.stringify(x))
 x=await request(port,'/api/attendance/mark',studentA,'POST',{student_id:1})
 assert.equal(x.status,403,JSON.stringify(x))
 // Finance and Paper Studio routes must refuse unqualified roles before queries.
 x=await request(port,'/api/fees/summary',teacherA)
 assert.equal(x.status,403,JSON.stringify(x))
 x=await request(port,'/api/paper-studio/papers',studentA)
 assert.equal(x.status,403,JSON.stringify(x))
 x=await request(port,'/api/paper-studio/papers',null)
 assert.equal(x.status,401,JSON.stringify(x))
 x=await request(port,'/api/fees/summary',adminA)
 assert.equal(x.status,200,JSON.stringify(x))
 x=await request(port,'/api/paper-studio/papers',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.length,1,JSON.stringify(x))
 assert.equal(x.json?.data?.[0]?.name,'P6 Synthetic Paper 900001')
 x=await request(port,'/api/paper-studio/papers',teacherBToken)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.length,1,JSON.stringify(x))
 assert.equal(x.json?.data?.[0]?.name,'P6 Synthetic Paper 900002')
 x=await request(port,'/api/paper-studio/papers',unassigned)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.length,0,JSON.stringify(x))
 x=await request(port,'/api/paper-studio/papers?school_id=900002',teacherA)
 assert.equal(x.status,200,JSON.stringify(x))
 assert.equal(x.json?.data?.[0]?.name,'P6 Synthetic Paper 900001')
})
