'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const read=relative=>fs.readFileSync(path.join(__dirname,'..',relative),'utf8')
test('database pool requires a separate non-BYPASS login and verifies effective runtime role',()=>{
 const code=read('config/database.js')
 assert.match(code,/DB_ENFORCE_LEAST_PRIVILEGE_LOGIN/)
 assert.match(code,/DB_PRIVILEGED_LOGIN_REJECTED/)
 assert.match(code,/DB_RUNTIME_ROLE_UNSAFE/)
 assert.match(code,/current_user AS role_name/)
 assert.match(code,/await resetRuntimeSession/)
})
test('signed tenant prebinding requires active school and matching tenant key',()=>{
 const code=read('middleware/auth.js')
 assert.match(code,/DB_AUTH_USE_SIGNED_TENANT_CONTEXT/)
 assert.match(code,/verifiedClaimSchoolId/)
 assert.match(code,/normalizeSchoolId\(activeUser.school_id\) !== verifiedClaimSchoolId/)
 assert.match(code,/canonicalUserTenant && canonicalSchoolTenant/)
 assert.match(code,/claimTenant && claimTenant !==/)
})
test('Assessment Results enforces role and actual teacher assignment before read/write',()=>{
 const code=read('routes/assessmentResultRoutes.js')
 assert.match(code,/router\.use\(protect, canEnterResults\)/)
 assert.match(code,/teacherCanAccessRelease/)
 assert.match(code,/teacherCanAccessClass/)
})
test('attendance enforces assigned classroom scope and requires marking roles',()=>{
 const code=read('routes/attendanceRoutes.js')
 assert.match(code,/canMarkAttendance = requireRoles/)
 assert.match(code,/teacherStudentScopeClause/)
 assert.match(code,/requireTeacherAssignmentsForAttendance/)
 assert.match(code,/router\.post\('\/mark', protect, canMarkAttendance/)
})
test('fees restrict summary and payments to authorized roles',()=>{
 const code=read('routes/feeRoutes.js')
 assert.match(code,/router\.get\('\/summary', protect, adminOnly/)
 assert.match(code,/canManageFeeRecord/)
 assert.match(code,/scopedFeeReadClause/)
})
test('canonical Paper Studio requires authenticated teacher-or-admin roles and scoped projection',()=>{
 const code=read('routes/paperStudioRoutes.js')
 assert.match(code,/router\.use\(protect, requireRoles\('super_admin','admin','principal','teacher'\)\)/)
 const projection=read('services/paperStudioProjectionService.js')
 assert.match(projection,/owner_user_id=\$\$\{params.length\}/)
 assert.match(projection,/WHERE school_id=\$1/)
})
test('Question Bank routes require authentication and role-bound management',()=>{
 const code=read('routes/questionBankRoutes.js')
 assert.match(code,/router\.use\(protect, canUseQuestionBank\)/)
 assert.match(code,/canManageQuestionBank/)
 assert.match(code,/teacher_class_assignments/)
})
test('Connect projection remains canonical SaaS-owned and must not create a second store',()=>{
 const code=read('services/paperStudioProjectionService.js')
 assert.match(code,/FROM paper_vault/)
 assert.match(code,/WHERE school_id=\$1/)
 const exposed=read('routes/paperStudioRoutes.js')
 assert.match(exposed,/getProjectedPaper/)
 assert.match(exposed,/listProjectedPapers/)
})
