# Phase 3G ONE-SHOT independently initialized disposable PostgreSQL18 cluster.
# NEVER connects to existing PostgreSQL service/port 5432 or uses application's .env.
# Contains only fictional school IDs and synthetic paper text. Stops its OWN cluster finally.
[CmdletBinding()]
param(
 [ValidateSet('RUN_SYNTHETIC_ONLY')][string]$Action
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if($Action -ne 'RUN_SYNTHETIC_ONLY'){throw 'Explicit RUN_SYNTHETIC_ONLY action is mandatory; refusing implicit DB initialization.'}
$bin='C:\Program Files\PostgreSQL\18\bin'
$port=55439
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$backend=Join-Path $repo 'al-siddique-backend\src'
$free=(Get-PSDrive -Name C).Free
if($free -lt 2GB){throw 'Refusing disposable PostgreSQL initialization while C drive has under 2 GB free.'}
$schema=Join-Path $PSScriptRoot 'phase3g-DISPOSABLE-ONLY-schema.sql'
foreach($file in @('initdb.exe','pg_ctl.exe','psql.exe','createdb.exe','pg_dump.exe','pg_restore.exe')){
 if(-not (Test-Path (Join-Path $bin $file))){throw ('PostgreSQL18 executable absent: '+$file)}
}
if(-not (Test-Path $schema)){throw 'Disposable schema missing.'}
if((Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue)){
 throw 'REFUSE: dedicated disposable port 55439 is already in use, do not inspect/connect it.'
}
$base=Join-Path $env:TEMP ('assps-phase3g-ephemeral-'+[guid]::NewGuid().ToString('N'))
if(Test-Path $base){throw 'Refuse pre-existing disposable directory collision.'}
New-Item -Path $base -ItemType Directory|Out-Null
$marker=Join-Path $base '.ASSPS_PHASE3G_SELF_CREATED'
Set-Content -Path $marker -Value '2026-10-02 Synthetic ASSPS Phase3G generated by its own script' -Encoding ASCII
$data=Join-Path $base 'data'
$log=Join-Path $base 'pg.log'
$pwfile=Join-Path $base 'initdb-password.txt'
$backup=Join-Path $base 'synthetic-only-PG18-backup.dump'
$manifest=Join-Path $base 'synthetic-phase3g-result.json'
$started=$false;$success=$false;$stopped=$false
$generator=[System.Security.Cryptography.RandomNumberGenerator]::Create()
function New-TestPassword {
 $bytes=New-Object byte[] 24
 $generator.GetBytes($bytes)
 return [BitConverter]::ToString($bytes).Replace('-','').ToLowerInvariant()
}
$adminPw=New-TestPassword
$appPw=New-TestPassword
function Require-Exit([string]$stage){
 if($LASTEXITCODE -ne 0){throw ('Disposable Phase3G '+$stage+' FAILED; exit='+$LASTEXITCODE)}
}
try{
 Write-Output 'PHASE3G_SANDBOX=NEW_RANDOM_DIRECTORY_LOOPBACK_55439_ONLY'
 Write-Output 'PHASE3G_EXISTING_POSTGRES_5432=NEVER_TOUCHED'
 Set-Content -Path $pwfile -Value $adminPw -Encoding ASCII -NoNewline
 & (Join-Path $bin 'initdb.exe') -D $data -U assps_p3g_admin -A scram-sha-256 "--pwfile=$pwfile" --encoding=UTF8 --locale=C
 Require-Exit 'initdb'
 Remove-Item -LiteralPath $pwfile -Force
 & (Join-Path $bin 'pg_ctl.exe') -D $data -l $log -o "-h 127.0.0.1 -p 55439 -c max_connections=30" -w start
 Require-Exit 'start cluster'
 $started=$true
 $env:PGHOST='127.0.0.1';$env:PGPORT='55439'
 $env:PGUSER='assps_p3g_admin';$env:PGPASSWORD=$adminPw
 # Role password is sent through psql STDIN, NEVER through shell/process command-line.
 ("CREATE ROLE assps_p3g_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD '"+$appPw+"';") |
  & (Join-Path $bin 'psql.exe') -X -v ON_ERROR_STOP=1 -d postgres
 Require-Exit 'create restricted synthetic role'
 & (Join-Path $bin 'createdb.exe') -E UTF8 -T template0 assps_paper_phase3f_ci
 Require-Exit 'create first synthetic database'
 & (Join-Path $bin 'psql.exe') -X -v ON_ERROR_STOP=1 -d assps_paper_phase3f_ci -f $schema
 Require-Exit 'apply strictly guarded DISPOSABLE schema'
 Write-Output 'PHASE3G_DISPOSABLE_SCHEMA=CREATED_ON_SEPARATE_SYNTHETIC_CLUSTER'
 $env:ASSPS_PHASE3G_REAL_PG='DISPOSABLE_CLUSTER_PORT_55439'
 $env:ASSPS_PHASE3G_ADMIN_URL="postgresql://assps_p3g_admin:$adminPw@127.0.0.1:55439/assps_paper_phase3f_ci"
 $env:ASSPS_PHASE3G_APP_URL="postgresql://assps_p3g_app:$appPw@127.0.0.1:55439/assps_paper_phase3f_ci"
 # Reuse already installed, verified frontend pg module; no npm install or package changes.
 $verifiedPgModules=Join-Path $repo 'al-siddique-frontend\node_modules'
 if(-not(Test-Path (Join-Path $verifiedPgModules 'pg'))){throw 'Verified existing node-postgres runtime missing; refuse network package install.'}
 $env:NODE_PATH=$verifiedPgModules
 Push-Location $backend
 try{
  & node --test 'tests/paperStagingDisposablePostgresPhase3G.test.js'
  Require-Exit 'REAL two-school SERIALIZABLE and RLS integration'
  $env:ASSPS_PHASE3F_READONLY_PG='YES_ISOLATED_STAGING_READONLY'
  $env:ASSPS_PHASE3F_STAGING_PG_URL=$env:ASSPS_PHASE3G_APP_URL
  & node --test 'tests/paperStagingReadOnlyPostgresPhase3F.test.js'
  Require-Exit 'REAL read-only catalog audit'
 }finally{Pop-Location}
 Write-Output 'PHASE3G_REAL_PG_INTEGRATION=PASSED_ON_ISOLATED_TEST_DB'
 & (Join-Path $bin 'pg_dump.exe') -Fc --file=$backup -d assps_paper_phase3f_ci
 Require-Exit 'custom-format encrypted-free SYNTHETIC archive creation'
 if((Get-Item $backup).Length -lt 2000){throw 'Synthetic PostgreSQL backup appears empty.'}
 $digest=(Get-FileHash -LiteralPath $backup -Algorithm SHA256).Hash.ToLowerInvariant()
 & (Join-Path $bin 'pg_restore.exe') --list $backup |Out-Null
 Require-Exit 'archive directory verification'
 & (Join-Path $bin 'createdb.exe') -E UTF8 -T template0 assps_paper_phase3g_restore_ci
 Require-Exit 'create FRESH separate restore database'
 & (Join-Path $bin 'pg_restore.exe') --exit-on-error -d assps_paper_phase3g_restore_ci $backup
 Require-Exit 'real PostgreSQL custom archive restore'
 $env:ASSPS_PHASE3G_RESTORE_URL="postgresql://assps_p3g_admin:$adminPw@127.0.0.1:55439/assps_paper_phase3g_restore_ci"
 Push-Location $backend
 try{
  & node --test 'tests/paperStagingRestorePhase3G.test.js'
  Require-Exit 'byte-exact restored fixture and audit verification'
 }finally{Pop-Location}
 $evidence=[ordered]@{
  format='ASSPS_PHASE3G_DISPOSABLE_SYNTHETIC_EVIDENCE_V1'
  syntheticOnly=$true
  actualPrincipalPaperApproved=$false
  actualProductionBackupVerified=$false
  active5432ServiceAccessed=$false
  isolatedPort=$port
  separateNewCluster=$true
  strictRlsTwoSchoolIntegration='REAL_PG_PASS'
  serializableConcurrency='REAL_PG_PASS'
  independentReadOnlySchemaAudit='REAL_PG_PASS_SYNTHETIC_ONLY'
  pgDumpCustomArchive='REAL_PASS_SYNTHETIC_ONLY'
  distinctDatabaseRestoreExactNativeJsonAndPolicies='REAL_PASS_SYNTHETIC_ONLY'
  backupSha256=$digest
  backupBytes=(Get-Item $backup).Length
  originalProductionSourcesChanged=$false
  backendDeploymentPerformed=$false
  manualPrincipalVisualSignoffStillRequired=$true
 }
 $evidence|ConvertTo-Json -Depth 5|Set-Content -Path $manifest -Encoding UTF8
 Write-Output ('PHASE3G_SYNTHETIC_BACKUP_SHA256='+$digest)
 Write-Output ('PHASE3G_SYNTHETIC_BACKUP_BYTES='+(Get-Item $backup).Length)
 Write-Output ('PHASE3G_EVIDENCE_MANIFEST='+$manifest)
 $success=$true
}finally{
 if(Test-Path $pwfile){Remove-Item -LiteralPath $pwfile -Force -ErrorAction SilentlyContinue}
 if($started){
  & (Join-Path $bin 'pg_ctl.exe') -D $data -m fast -w stop
  if($LASTEXITCODE -eq 0){$stopped=$true;Write-Output 'PHASE3G_DISPOSABLE_CLUSTER=STOPPED'}
  else{Write-Warning 'Self-created disposable cluster did not confirm stop; retain for inspection.'}
 }
 foreach($name in @('PGHOST','PGPORT','PGUSER','PGPASSWORD','ASSPS_PHASE3G_REAL_PG',
  'ASSPS_PHASE3G_ADMIN_URL','ASSPS_PHASE3G_APP_URL','ASSPS_PHASE3G_RESTORE_URL',
  'ASSPS_PHASE3F_READONLY_PG','ASSPS_PHASE3F_STAGING_PG_URL','NODE_PATH')){
  Remove-Item ('Env:'+$name) -ErrorAction SilentlyContinue
 }
 $adminPw=$null;$appPw=$null;$generator.Dispose()
 if($success -and $stopped -and (Test-Path $marker) -and
   $base.StartsWith((Join-Path $env:TEMP 'assps-phase3g-ephemeral-'),
    [System.StringComparison]::OrdinalIgnoreCase)){
  # Remove ONLY our self-created STOPPED cluster DATA directory to protect C: capacity.
  # Retain tiny fake-only archive, log and no-secret JSON report for reproducible evidence.
  Remove-Item -LiteralPath $data -Force -Recurse
  Write-Output 'PHASE3G_ONLY_SELF_CREATED_CLUSTER_DATA=REMOVED_AFTER_VERIFIED_STOP'
 }
}
if(-not $success){throw 'Phase3G disposable real PostgreSQL verification incomplete.'}
Write-Output 'PHASE3G_DISPOSABLE_REAL_POSTGRES_AND_RESTORE=COMPLETE_SYNTHETIC_ONLY'
