import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateQuestion,duplicateDiagnostics,selectApprovedQuestions} from './questionContract.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(name,import.meta.url),'utf8'));
const datasets=[1,2,3,4].map(ch=>({chapter:ch,source:read(`./chemistry9Chapter${ch}ContentMap2026.json`),bank:read(`./chemistry9Chapter${ch}EnglishDrafts2026.json`)}));
const all=datasets.flatMap(x=>x.bank.drafts);
test('cross-chapter Chemistry IX draft IDs and academic stem signatures remain unique',()=>{assert.equal(all.length,111);assert.deepEqual(duplicateDiagnostics(all),[]);assert.equal(new Set(all.map(q=>q.id)).size,all.length);});
test('all Chemistry IX drafts remain chapter-bound to the verified current source',()=>{for(const d of datasets){for(const q of d.bank.drafts){assert.equal(q.chapter.number,d.chapter,q.id);assert.equal(q.source.catalogRecordId,'pectaa-catalog-007');assert.equal(q.source.pdfSha256,d.source.sourcePdfSha256);assert(q.source.page>=d.source.chapter.pdfPages[0]&&q.source.page<=d.source.chapter.pdfPages[1],q.id);assert.equal(q.curriculum.edition,'2025-26');assert.equal(q.medium,'english');assert.equal(validateQuestion(q).valid,true,q.id);}}});
test('cross-chapter drafts cannot be silently promoted or treated as validated translations',()=>{for(const d of datasets){assert.equal(d.bank.publicationAllowed,false);assert.equal(d.bank.liveImportAllowed,false);}assert.equal(selectApprovedQuestions(all,{medium:'english'}).length,0);for(const q of all){assert.equal(q.review.status,'draft');assert(Object.values(q.review.checks).every(x=>x===false));assert.equal(q.boardEvidence.length,0);assert.equal(q.origin==='exercise',false);}});
test('each current chapter and numbered topic has at least one unapproved original English concept draft',()=>{for(const d of datasets){assert(d.bank.topicCoverage.every(x=>x.draftCount>=2));for(const t of d.source.topics)assert(d.bank.drafts.some(q=>q.topicId===t.topicId));}});
