import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const d=JSON.parse(fs.readFileSync(new URL('./officialGrade9MatricTechPattern2026.json',import.meta.url),'utf8'));
const sum=o=>Object.values(o||{}).reduce((a,b)=>a+b,0);
test('official Matric-Tech bundle is hash locked and covers ten distinct Grade IX subjects',()=>{assert.match(d.artifact.sha256,/^[a-f0-9]{64}$/);assert.equal(d.artifact.pageCount,40);assert.equal(d.subjects.length,10);assert.equal(new Set(d.subjects.map(x=>x.subject)).size,10);});
test('every Matric-Tech structure reconciles marks without copying paper stems',()=>{for(const s of d.subjects){const short=s.shortQuestions.reduce((a,q)=>a+q.attempt*q.marksEach,0);const long=s.longQuestions.attempt*s.longQuestions.marksEach;assert.equal(s.objective.marks+short+long,s.totalMarks,s.subject);assert.equal(s.durationMinutes,120);}assert.equal(d.guards.patternOnlyNoQuestionStemCopy,true);});
test('encoded chapter distributions reconcile only where visually clear',()=>{for(const s of d.subjects){if(s.objective.chapterCounts)assert.equal(sum(s.objective.chapterCounts),s.objective.mcqs);for(const q of s.shortQuestions)if(q.chapterCounts)assert.equal(sum(q.chapterCounts),q.offered);}});
test('all Matric-Tech chapter distributions are now evidence-resolved without disabling fail-closed policy',()=>{const ambiguous=d.subjects.filter(s=>s.objective.distributionState||s.shortQuestions.some(q=>q.distributionState)||s.longQuestions.distributionState);assert.deepEqual(ambiguous,[]);assert.equal(d.guards.unclearOCRDistributionNeverGuessed,true);const health=d.subjects.find(x=>x.subject==='Health Sciences-Tech');assert.equal(health.evidenceResolution,'HIGH_RES_PAIRING_TABLE_OCR_REVIEW');const chem=d.subjects.find(x=>x.subject==='Chemistry-Tech');assert.equal(chem.evidenceResolution,'PAIRING_PLUS_MODEL_CONTENT_CROSSCHECK');const bio=d.subjects.find(x=>x.subject==='Biology-Tech');assert.equal(bio.evidenceResolution,'PAIRING_TABLE_PLUS_MODEL_CONTENT_CROSSCHECK');});
test('Matric-Tech identity cannot collapse into mainstream subject identity',()=>{assert.equal(d.guards.matricTechNeverMergedWithMainstreamBySimilarSubjectName,true);assert(d.subjects.some(x=>x.subject==='Physics-Tech'));assert(d.subjects.some(x=>x.subject==='Computer Science & Entrepreneurship-Tech'));});

test('Computer-Tech long numbering is corrected by subjective model cross-check',()=>{const s=d.subjects.find(x=>x.subject==='Computer Science & Entrepreneurship-Tech');assert.deepEqual(s.longQuestions.questionNumbers,[4,5,6]);assert.deepEqual(s.longQuestions.questionChapterChoices['4'],[5]);assert.deepEqual(s.longQuestions.questionChapterChoices['5'],[7]);assert.deepEqual(s.longQuestions.questionChapterChoices['6'],[2,10]);assert.equal(s.evidenceResolution,'MODEL_PAPER_NUMBERING_CROSSCHECK');});
