import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const d=JSON.parse(fs.readFileSync(new URL('./officialGrade9MatricTechPracticalPattern2026.json',import.meta.url),'utf8'));
const nums=v=>Array.isArray(v)?v:(v?.practicals||[]);
test('official practical package is notification/hash/page locked',()=>{assert.equal(d.notification.number,'PECTAA/C&C Unit/2026/551');assert.equal(d.notification.date,'2026-01-08');assert.match(d.artifact.sha256,/^[a-f0-9]{64}$/);assert.equal(d.artifact.pageCount,17);assert.equal(d.subjects.length,4);});
test('all practical papers reconcile 12+12+6+5 to 35 marks',()=>{for(const s of d.subjects){const x=s.sections;assert.equal(x.q1.marks+x.q2.marks+x.practicalNotebook.marks+x.vivaVoce.marks,35,s.subject);assert.equal(s.totalMarks,35);assert.equal(s.durationMinutes,120);}});
test('pairing pools stay inside each subject practical inventory',()=>{for(const s of d.subjects){for(const q of [s.sections.q1,s.sections.q2])for(const pool of [q.poolA,q.poolB]){const a=nums(pool);assert(a.length>0,s.subject);assert(a.every(n=>Number.isInteger(n)&&n>=1&&n<=s.practicalCount),s.subject);}}});
test('Fashion and ICT unit ranges cover their practical inventories exactly',()=>{for(const subject of ['Fashion Designing-Tech','Information & Communication Technologies-Tech']){const s=d.subjects.find(x=>x.subject===subject);const seen=[];for(const [a,b] of Object.values(s.unitRanges))for(let n=a;n<=b;n++)seen.push(n);assert.deepEqual(seen,[...Array(s.practicalCount)].map((_,i)=>i+1));}});
test('ICT selected practical keeps execution/procedure 5+7 child split',()=>{const s=d.subjects.find(x=>x.subject==='Information & Communication Technologies-Tech');assert.deepEqual(s.modelTaskSplit,{executionMarks:5,writtenProcedureMarks:7,totalPerSelectedPractical:12});});
test('practical track cannot be collapsed into theory or copy model wording',()=>{assert.equal(d.rules.practicalAndTheoryRemainSeparateDimensions,true);assert.equal(d.rules.patternOnlyNotAcademicContentAuthority,true);assert.equal(d.rules.copyModelTaskWordingIntoQuestionBank,false);assert.equal(d.rules.preserveASSPSVisualTemplate,true);});
