import { test, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { createServer } from 'vite'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const front=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../../..')
let vite, browser, page
before(async()=>{
 vite=await createServer({root:front,server:{port:5393,strictPort:true}});await vite.listen()
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-setuid-sandbox']})
 page=await browser.newPage({viewport:{width:1650,height:1100}})
 await page.route('**/api/settings/public**',route=>route.fulfill({status:200,contentType:'application/json',body:'{}'}))
 await page.goto('http://127.0.0.1:5393/paper-workspace-test.html',{waitUntil:'domcontentloaded'})
 await page.locator('[data-paper-style-root]').waitFor({timeout:15000})
})
after(async()=>{await browser?.close();await vite?.close()})
test('real Chromium mouse drag selects serial plus Urdu instruction, never marks, and styles persist',async()=>{
 await page.getByRole('button',{name:'Edit Paper'}).click()
 const holder=page.locator('[data-question-heading]').filter({has:page.locator('[data-edit-field="question-number"]')}).first()
 const serial=holder.locator('[data-edit-field="question-number"]')
 const heading=holder.locator('[data-edit-field="question-heading"]')
 const mark=page.locator('[data-marks-badge]').first()
 const originalSerial=await serial.textContent(), originalHeading=await heading.textContent(),originalMark=await mark.textContent()
 const unrelated=page.locator('[data-question-heading]').nth(1),unrelatedBefore=await unrelated.locator('[data-edit-field="question-heading"]').innerHTML()
 assert.ok(originalSerial.length>4&&originalHeading.length>7)
 const a=await serial.boundingBox(),b=await heading.boundingBox();assert.ok(a&&b)
 // Genuine mouse events are dispatched into the two independent edit roots.
 await page.mouse.move(a.x+a.width*0.46,a.y+a.height*0.52)
 await page.mouse.down()
 const headingEnd=await heading.evaluate(el=>{
  const node=document.createTreeWalker(el,NodeFilter.SHOW_TEXT).nextNode()
  const range=document.createRange();range.setStart(node,0);range.setEnd(node,Math.min(7,node.textContent.length))
  const rect=range.getBoundingClientRect()
  return {x:rect.left+2,y:rect.top+rect.height/2}
 })
 await page.mouse.move(headingEnd.x,headingEnd.y,{steps:20})
 await page.mouse.up()
 const selected=await page.evaluate(()=>window.getSelection()?.toString()||'')
 assert.ok(selected.length>1&&selected.includes(originalSerial.slice(-2)),'Literal serial glyphs must be inside native selection')
 assert.ok(selected.includes(originalHeading.slice(0,1)),'Literal heading glyphs must be inside native selection')
 assert.ok(!selected.includes(originalMark.trim()),'Marks must not be dragged into question formatting')
 const toolbar=page.locator('[data-inline-selection-toolbar]')
 await toolbar.getByRole('button',{name:'B',exact:true}).click()
 await toolbar.getByRole('button',{name:'I',exact:true}).click()
 await toolbar.getByRole('button',{name:'U',exact:true}).click()
 const serialHtml=await serial.innerHTML(),headingHtml=await heading.innerHTML()
 for(const html of [serialHtml,headingHtml]){
  assert.match(html,/font-weight:\s*bold|<b>|<strong>/i)
  assert.match(html,/font-style:\s*italic|<i>|<em>/i)
  assert.match(html,/text-decoration(?:-line)?:\s*underline|<u>/i)
 }
 assert.equal(await mark.textContent(),originalMark)
 assert.equal(await serial.textContent(),originalSerial)
 assert.equal(await heading.textContent(),originalHeading)
 // Opening words are formatted but the untouched sentence suffix remains plain.
 const suffixIsPlain=await heading.evaluate(el=>{
  const text=el.textContent||''
  const trailing=[...el.childNodes].reverse().find(node=>node.nodeType===Node.TEXT_NODE && node.textContent.trim())
  return Boolean(trailing && text.endsWith(trailing.textContent))
 })
 assert.equal(suffixIsPlain,true,'Cross-field formatting leaked into unselected Urdu suffix')
 // A single undo/redo must act on both affected roots, not another question.
 await toolbar.getByRole('button',{name:'Undo'}).click()
 assert.doesNotMatch(await serial.innerHTML(),/text-decoration(?:-line)?:\s*underline|<u>/i)
 assert.doesNotMatch(await heading.innerHTML(),/text-decoration(?:-line)?:\s*underline|<u>/i)
 await toolbar.getByRole('button',{name:'Redo'}).click()
 assert.match(await serial.innerHTML(),/text-decoration(?:-line)?:\s*underline|<u>/i)
 assert.match(await heading.innerHTML(),/text-decoration(?:-line)?:\s*underline|<u>/i)
 await toolbar.getByRole('button',{name:'B',exact:true}).click()
 assert.doesNotMatch(await serial.innerHTML(),/font-weight:\s*bold|<b>|<strong>/i,'Bold toggle off should clear selected serial styling')
 assert.doesNotMatch(await heading.innerHTML(),/font-weight:\s*bold|<b>|<strong>/i,'Bold toggle off should clear selected heading styling')
 await toolbar.getByRole('button',{name:'B',exact:true}).click()
 assert.match(await serial.innerHTML(),/font-weight:\s*bold|<b>/i)
 assert.match(await heading.innerHTML(),/font-weight:\s*bold|<b>/i)
 await page.getByRole('button',{name:'Done Editing'}).click()
 assert.equal(await mark.textContent(),originalMark)
 assert.match(await serial.innerHTML(),/font-weight:\s*bold/i)
 assert.match(await heading.innerHTML(),/font-weight:\s*bold/i)
 assert.equal(await unrelated.locator('[data-edit-field="question-heading"]').innerHTML(),unrelatedBefore,'Another question heading content was unexpectedly modified')
 console.log('CROSS_FIELD_NATIVE_DRAG_BROWSER_PASS')
})


test('English LTR serial and instruction share native drag without marks or other question leak', async()=>{
 await page.goto('http://127.0.0.1:5393/paper-workspace-test.html?nestedScoring',{waitUntil:'domcontentloaded'})
 await page.locator('[data-paper-style-root]').waitFor({timeout:12000})
 await page.getByRole('button',{name:'Edit Paper'}).click()
 const root=page.locator('[data-question-heading]').filter({has:page.locator('[data-edit-field="question-number"]')}).first()
 const serial=root.locator('[data-edit-field="question-number"]'),heading=root.locator('[data-edit-field="question-heading"]')
 const badge=page.locator('[data-marks-badge]').first()
 const serialText=await serial.textContent(),headingText=await heading.textContent(),marks=await badge.textContent()
 const a=await serial.boundingBox(),b=await heading.boundingBox()
 assert.ok(a&&b)
 await page.mouse.move(a.x+a.width*.35,a.y+a.height*.55)
 await page.mouse.down()
 await page.mouse.move(b.x+Math.min(b.width*.42,150),b.y+b.height*.55,{steps:17})
 await page.mouse.up()
 const chosen=await page.evaluate(()=>window.getSelection()?.toString()||'')
 assert.ok(chosen.includes(serialText.slice(-1))&&chosen.includes(headingText.slice(0,3)),`cross-root native selection: ${chosen}`)
 const bar=page.locator('[data-inline-selection-toolbar]')
 await bar.getByRole('button',{name:'B',exact:true}).click()
 assert.match(await serial.innerHTML(),/font-weight:\s*bold|<b>/i)
 assert.match(await heading.innerHTML(),/font-weight:\s*bold|<b>/i)
 assert.equal(await badge.textContent(),marks)
 assert.equal(await serial.textContent(),serialText)
 assert.equal(await heading.textContent(),headingText)
 console.log('CROSS_FIELD_ENGLISH_LTR_BROWSER_PASS')
})


test('reversed English drag preserves logical direction and marks editing does not reuse stale cross selection',async()=>{
 await page.goto('http://127.0.0.1:5393/paper-workspace-test.html?nestedScoring',{waitUntil:'domcontentloaded'})
 await page.locator('[data-paper-style-root]').waitFor({timeout:12000})
 await page.getByRole('button',{name:'Edit Paper'}).click()
 const root=page.locator('[data-question-heading]').filter({has:page.locator('[data-edit-field="question-number"]')}).first()
 const serial=root.locator('[data-edit-field="question-number"]'),heading=root.locator('[data-edit-field="question-heading"]')
 const badge=page.locator('[data-marks-badge]').first()
 const a=await serial.boundingBox(),b=await heading.boundingBox()
 await page.mouse.move(b.x+Math.min(150,b.width*.30),b.y+b.height*.52)
 await page.mouse.down()
 await page.mouse.move(a.x+a.width*.4,a.y+a.height*.52,{steps:17})
 await page.mouse.up()
 const selection=await page.evaluate(()=>window.getSelection()?.toString()||'')
 assert.ok(selection.includes((await serial.textContent()).slice(-1))&&selection.includes((await heading.textContent()).slice(0,3)),`reverse drag failed: ${selection}`)
 const bar=page.locator('[data-inline-selection-toolbar]')
 await bar.getByRole('button',{name:'B',exact:true}).click()
 assert.match(await serial.innerHTML(),/font-weight:\s*bold|<b>/i)
 assert.match(await heading.innerHTML(),/font-weight:\s*bold|<b>/i)
 // Focus marks: the previous composite range must not format the old heading.
 const previousSerial=await serial.innerHTML(),previousHeading=await heading.innerHTML()
 await badge.locator('[data-edit-field="marks"]').click()
 await bar.getByRole('button',{name:'I',exact:true}).click()
 assert.equal(await serial.innerHTML(),previousSerial)
 assert.equal(await heading.innerHTML(),previousHeading)
 console.log('CROSS_FIELD_REVERSE_AND_MARKS_ISOLATION_PASS')
})


test('shared edit root still accepts independent heading text editing and persists canonical marks',async()=>{
 await page.goto('http://127.0.0.1:5393/paper-workspace-test.html?nestedScoring',{waitUntil:'domcontentloaded'})
 await page.locator('[data-paper-style-root]').waitFor({timeout:12000})
 await page.getByRole('button',{name:'Edit Paper'}).click()
 const root=page.locator('[data-question-heading]').filter({has:page.locator('[data-edit-field="question-number"]')}).first()
 const serial=root.locator('[data-edit-field="question-number"]'),heading=root.locator('[data-edit-field="question-heading"]')
 const before=await heading.textContent(),num=await serial.textContent(),mark=await page.locator('[data-marks-badge]').first().textContent()
 await heading.evaluate(el=>{
  const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT)
  let last=null,node;while((node=walker.nextNode()))last=node
  const range=document.createRange();range.setStart(last,last.textContent.length);range.collapse(true)
  const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range)
 })
 await page.keyboard.insertText(' EXTRA')
 await page.getByRole('button',{name:'Done Editing'}).click()
 assert.ok((await heading.textContent()).includes('EXTRA'),'Heading text must remain editable and persist independently')
 assert.ok((await heading.textContent()).startsWith(before),'Original instruction must not disappear')
 assert.equal(await serial.textContent(),num)
 assert.equal(Number((await page.locator('[data-marks-badge]').first().textContent()).match(/\d+/)?.[0]),Number(mark.match(/\d+/)?.[0]),'Numeric marks must stay unchanged across view/edit labels')
 console.log('HEADING_TEXT_EDIT_PERSISTENCE_BROWSER_PASS')
})


test('cross-field selection refuses destructive deletion while allowing formatting',async()=>{
 await page.goto('http://127.0.0.1:5393/paper-workspace-test.html?nestedScoring',{waitUntil:'domcontentloaded'})
 await page.locator('[data-paper-style-root]').waitFor({timeout:12000})
 await page.getByRole('button',{name:'Edit Paper'}).click()
 const root=page.locator('[data-question-heading]').filter({has:page.locator('[data-edit-field="question-number"]')}).first()
 const serial=root.locator('[data-edit-field="question-number"]'),heading=root.locator('[data-edit-field="question-heading"]')
 const a=await serial.boundingBox(),b=await heading.boundingBox()
 const oldSerial=await serial.textContent(),oldHeading=await heading.textContent()
 await page.mouse.move(a.x+a.width*.35,a.y+a.height*.5);await page.mouse.down()
 await page.mouse.move(b.x+Math.min(150,b.width*.4),b.y+b.height*.5,{steps:15});await page.mouse.up()
 const selected=await page.evaluate(()=>window.getSelection()?.toString()||'')
 assert.ok(selected.includes(oldSerial.slice(-1))&&selected.includes(oldHeading.slice(0,2)))
 await page.keyboard.press('Backspace')
 assert.equal(await serial.textContent(),oldSerial,'Backspace must not delete serial across stored field boundary')
 assert.equal(await heading.textContent(),oldHeading,'Backspace must not delete instruction across stored field boundary')
 const bar=page.locator('[data-inline-selection-toolbar]')
 await bar.getByRole('button',{name:'B',exact:true}).click()
 assert.match(await serial.innerHTML(),/font-weight:\s*bold|<b>/i)
 assert.match(await heading.innerHTML(),/font-weight:\s*bold|<b>/i)
 console.log('CROSS_FIELD_DELETE_GUARD_BROWSER_PASS')
})
