'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const crypto=require('node:crypto')
const {build,SOURCE,OUTPUT,DOCKET,PROPOSALS}=require('../qbank/build-bio9-research-urdu-editorial-rev2.cjs')
const {inspect}=require('../qbank/audit-bilingual-structural-parity.cjs')
const sha=x=>crypto.createHash('sha256').update(x).digest('hex')
const sourceBytes=fs.readFileSync(SOURCE)
const original=JSON.parse(sourceBytes)
const actual=build(sourceBytes)
test('four unique original Grade IX Biology research short questions retained, not four new authored questions',()=>{
 const ids=Object.keys(PROPOSALS).sort()
 assert.deepEqual(actual.full.questions.map(q=>q.id),ids)
 assert.equal(ids.length,4)
 assert.equal(new Set(ids).size,4)
 assert.equal(actual.full.uniqueQuestionsAdded,0)
 assert.equal(actual.full.academicallyApproved,false)
 assert.equal(actual.full.releaseEligible,false)
 assert.equal(actual.full.liveImportAllowed,false)
 assert.equal(actual.full.translationIndependentlyReviewed,false)
 assert.equal(actual.full.schoolAdoptedBookVerified,false)
 assert.equal(actual.full.sourcePrintedPageVerified,false)
 assert.equal(sha(sourceBytes),actual.full.parentAuthoringSha256)
})
test('English question, answer, original stable ID, marks, topic and official source are byte-for-byte unchanged',()=>{
 for(const next of actual.full.questions){
  const prev=original.drafts.find(q=>q.id===next.id)
  assert.ok(prev,next.id)
  assert.deepEqual(next.content.en,prev.content.en)
  assert.deepEqual(next.content.hi,prev.content.hi)
  assert.equal(next.id,prev.id)
  assert.equal(next.type,prev.type)
  assert.equal(next.marks,prev.marks)
  assert.deepEqual(next.chapter,prev.chapter)
  assert.equal(next.topicId,prev.topicId)
  assert.deepEqual(next.source,prev.source)
  assert.deepEqual(next.curriculum,prev.curriculum)
  assert.equal(next.editorialRevision.parentQuestionSha256,sha(JSON.stringify(prev)))
 }
})
test('each proposed Urdu stem and answer is present without promoting the question or losing unresolved expert-review flags',()=>{
 for(const q of actual.full.questions){
  assert.match(q.content.ur.stem,/\p{Script=Arabic}/u)
  assert.match(q.content.ur.answer,/\p{Script=Arabic}/u)
  assert.ok(q.content.ur.stem.length>=70)
  assert.ok(q.content.ur.answer.length>=110)
  assert.deepEqual(inspect(q).structuralIssues,[])
  assert.equal(q.review.status,'draft')
  assert.ok(Object.values(q.review.checks).every(v=>v===false))
  assert.equal(q.editorialRevision.semanticEquivalencePending,true)
  assert.equal(q.editorialRevision.terminologyReviewPending,true)
  assert.equal(q.editorialRevision.type,'INDEPENDENT_HUMAN_REVIEW_REQUIRED')
  assert.equal(q.editorialRevision.questionOrigin,'ORIGINAL_CONCEPTUAL_NOT_TEXTBOOK_EXERCISE')
 }
})
test('full revision, parent question and review docket SHA-256 fingerprints are deterministic and revision bound',()=>{
 assert.equal(sha(actual.bytes),sha(fs.readFileSync(OUTPUT)))
 assert.deepEqual(actual.bytes,fs.readFileSync(OUTPUT))
 assert.deepEqual(actual.reviewBytes,fs.readFileSync(DOCKET))
 assert.equal(actual.docket.revisionFileSha256,sha(actual.bytes))
 assert.equal(actual.docket.originalFileSha256,sha(sourceBytes))
 assert.equal(actual.docket.questionCount,4)
 for(const item of actual.docket.items){
  const q=actual.full.questions.find(q=>q.id===item.questionId)
  const prev=original.drafts.find(q=>q.id===item.questionId)
  assert.equal(item.originalQuestionSha256,sha(JSON.stringify(prev)))
  assert.equal(item.proposedRevisionSha256,sha(JSON.stringify(q)))
  assert.equal(item.sourcePageVerified,false)
  assert.equal(item.semanticEquivalenceVerified,false)
  assert.equal(item.approved,false)
  assert.equal(item.published,false)
  assert.equal(item.reviewerId,null)
  assert.equal(item.independentAcademicReviewerId,null)
 }
 assert.equal(actual.docket.sourceVerified,0)
 assert.equal(actual.docket.translationReviewed,0)
 assert.equal(actual.docket.academicReviewed,0)
 assert.equal(actual.docket.approved,0)
 assert.equal(actual.docket.published,0)
})
test('source drift cannot silently regenerate or inherit editorial review',()=>{
 const changed=Buffer.from(sourceBytes)
 changed[changed.length-3]=changed[changed.length-3]===32?10:32
 assert.throws(()=>build(changed),/PARENT_SOURCE_BYTES_CHANGED/)
})
test('potential microbiology versus mycology ambiguity is an explicit science review item rather than silently certified',()=>{
 const item=actual.docket.items.find(x=>x.questionId.endsWith('S01'))
 assert.equal(item.scientificScopeFlag,'MICROBIOLOGY_VS_MYCOLOGY_TERMINOLOGY_CONFIRMATION')
 assert.ok(actual.full.questions.every(q=>q.editorialRevision.schoolAdoptedBookVerified===false))
})
