'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const crypto=require('node:crypto')
const {build,markdown,ANSWERS,SECOND_SET,ORIGINAL_SHA}=require('../qbank/author-biology9-twenty-two-long-answers.cjs')
const ROOT=path.resolve(__dirname,'../..')
const input=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging/biology9EnglishStarter2026.json')
const bytes=fs.readFileSync(input),source=JSON.parse(bytes)
const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'al-siddique-backend/src/data/verifiedGrade910SourceRegistry.json')))
const digest=x=>crypto.createHash('sha256').update(x).digest('hex')
const run=(b=bytes,s=source,r=registry)=>build({bytes:b,source:s,registry:r})
test('authentic Grade IX Biology corpus yields all 22 original long answers, two from each of eleven chapters',()=>{
 const d=run()
 assert.equal(digest(bytes),ORIGINAL_SHA)
 assert.equal(d.originalAuthoredQuestions,66)
 assert.equal(d.originalLongQuestionCount,22)
 assert.equal(d.newlyAuthoredLongAnswerDrafts,22)
 assert.equal(d.newlyAuthoredSeparateMarkingPoints,110)
 assert.equal(d.remainingRubricOnlyLongQuestionIds.length,0)
 assert.deepEqual(d.items.map(x=>x.chapterNo),[1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11])
 assert.deepEqual(d.items.map(x=>x.questionId),source.drafts.filter(q=>q.type==='long').map(x=>x.id))
 assert.equal(d.approved,0);assert.equal(d.published,0)
})
test('all new explanations contain actual substantive teaching answer text and a separately recorded five-mark guide',()=>{
 const d=run(),originals=new Map(source.drafts.map(x=>[x.id,x]))
 assert.equal(Object.keys(ANSWERS).length,11)
 assert.equal(Object.keys(SECOND_SET).length,11)
 for(const x of d.items){
  const q=originals.get(x.questionId)
  assert.ok(q)
  assert.ok(x.proposedEnglishModelAnswer.length>=200)
  assert.notEqual(x.proposedEnglishModelAnswer,q.content.en.answer)
  assert.ok(!/^\s*award\s/i.test(x.proposedEnglishModelAnswer))
  assert.equal(x.proposedSeparateMarkingCriteria.length,5)
  assert.equal(new Set(x.proposedSeparateMarkingCriteria).size,5)
  assert.equal(x.marks,5)
  assert.equal(x.chapterNo,q.chapter.number)
  assert.equal(x.topicId,q.topicId)
  assert.equal(x.originalQuestionSha256,digest(JSON.stringify(q)))
  assert.equal(x.originalAnswerSha256,digest(q.content.en.answer))
  assert.equal(x.sourceFileSha256,ORIGINAL_SHA)
  assert.equal(x.originalQuestionAnswerUnmodified,true)
  assert.equal(x.qualifiedSubjectReviewed,false)
  assert.equal(x.schoolBookEditionAndPageVerified,false)
  assert.equal(x.englishUrduEquivalenceVerified,false)
  assert.equal(x.independentReviewerId,null)
  assert.equal(x.approvedQuestionRevisionId,null)
  assert.equal(x.approved,false)
  assert.equal(x.published,false)
 }
})
test('sample biological knowledge statements are specific and do not confuse cell division and enzymes',()=>{
 const d=run(),map=new Map(d.items.map(x=>[x.questionId,x.proposedEnglishModelAnswer]))
 assert.match(map.get('IX-BIO-2025-C04-B01-L01'),/S phase/)
 assert.match(map.get('IX-BIO-2025-C04-B01-L01'),/cytokinesis/i)
 assert.match(map.get('IX-BIO-2025-C07-B01-L01'),/active site/i)
 assert.match(map.get('IX-BIO-2025-C07-B01-L01'),/not consumed overall/i)
 assert.match(map.get('IX-BIO-2025-C11-B01-L01'),/outlier/i)
 assert.match(map.get('IX-BIO-2025-C02-B01-L01'),/domain, kingdom, phylum, class, order, family, genus and species/i)
})
test('tampered original long answer or unrelated question invalidates exact research source snapshot',()=>{
 for(const id of ['IX-BIO-2025-C01-B01-L01','IX-BIO-2025-C11-B02-M01']){
  const s=structuredClone(source)
  const q=s.drafts.find(x=>x.id===id)
  assert.ok(q,id)
  q.content.en.answer='A different unreviewed revision'
  assert.throws(()=>run(Buffer.from(JSON.stringify(s)),s),/BIO9_ANSWER_SNAPSHOT_CHANGED/)
 }
})
test('a modified in-memory original cannot pretend to be signed source bytes',()=>{
 const s=structuredClone(source)
 s.drafts[0].content.en.answer='Changed in memory only'
 assert.throws(()=>run(bytes,s),/BIO9_ANSWER_SNAPSHOT_CHANGED/)
})
test('forged source register identity is rejected before any review proposal creation',()=>{
 const r=structuredClone(registry)
 const c=r.entries.find(x=>x.recordId===source.sourceRecordId)
 c.pdfSha256='0'.repeat(64)
 assert.throws(()=>run(bytes,source,r),/BIO9_SOURCE_REGISTRY_DRIFT/)
})
test('unknown original source without school registry entry is rejected',()=>{
 const r=structuredClone(registry)
 r.entries=r.entries.filter(x=>x.recordId!==source.sourceRecordId)
 assert.throws(()=>run(bytes,source,r),/BIO9_SOURCE_REGISTRY_DRIFT/)
})
test('faculty packet has full eleven explanatory answers but does not imply verification or completed signoff',()=>{
 const d=run(),md=markdown(d)
 assert.ok(md.includes('twenty-two independently authored long-answer proposals'))
 assert.ok(md.includes('Remaining rubric-only original question IDs'))
 assert.ok(md.includes('Qualified teacher reviewed 0'))
 assert.ok(md.includes('source/page verified 0'))
 assert.ok(md.includes('SaaS Core alone certifies'))
 assert.equal(d.qualifiedTeacherReviewed,0)
 assert.equal(d.items.every(x=>!x.approved&&!x.published),true)
})
test('there are no unaddressed Grade IX Biology long question IDs in this separate authoring batch',()=>{
 const d=run(),longIds=new Set(source.drafts.filter(q=>q.type==='long').map(x=>x.id))
 assert.equal(new Set(d.remainingRubricOnlyLongQuestionIds).size,0)
 assert.ok(d.remainingRubricOnlyLongQuestionIds.every(id=>longIds.has(id)))
 assert.equal(new Set(d.items.map(x=>x.questionId)).size,22)
})
