'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const crypto=require('node:crypto')
const {build,IN,OUT,DOCKET,FILES,canonicalOptions}=require('../qbank/build-chemistry9-mcq-editorial-rev2.cjs')
const {verify}=require('../qbank/verify-chemistry9-mcq-editorial-rev2.cjs')
const {inspectMcqs}=require('../qbank/audit-mcq-key-patterns.cjs')
const {collectDocuments}=require('../qbank/audit-authoring-crossfile-qa.cjs')
const {buildReviewQueue}=require('../qbank/build-grade910-review-triage.cjs')
const {loadCandidates}=require('../qbank/verify-bio9-editorial-translation-proposals.cjs')
const manifest=require('../../al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging/officialSourceManifest.json')
const SHA=x=>crypto.createHash('sha256').update(x).digest('hex')
const clone=x=>JSON.parse(JSON.stringify(x))
const generated=build()
const originalDocs=FILES.map(f=>JSON.parse(fs.readFileSync(path.join(IN,f.file),'utf8')))
const reviewLinks=verify()
test('twenty Chemistry IX chapter 10 and 13 MCQ editorial revisions have unchanged source ids and no new original question IDs',()=>{
 assert.equal(generated.packageData.questions.length,20)
 assert.deepEqual(generated.packageData.chapters,[10,13])
 assert.deepEqual(generated.packageData.originalKeyDistribution,{A:20,B:0,C:0,D:0})
 assert.deepEqual(generated.packageData.proposedKeyDistribution,{A:5,B:5,C:5,D:5})
 assert.equal(generated.packageData.newQuestionCount,0)
 assert.equal(generated.packageData.releaseEligible,false)
 assert.equal(generated.packageData.liveImportAllowed,false)
 assert.equal(generated.packageData.approved,false)
 assert.equal(generated.packageData.published,false)
 assert.equal(generated.docket.approved,0)
 assert.equal(generated.docket.published,0)
})
test('question answer text stays pointed to the original correct choice even after the option reorder',()=>{
 const originalMap=new Map(originalDocs.flatMap(d=>d.drafts.filter(q=>q.type==='mcq').map(q=>[q.id,q])))
 assert.equal(originalMap.size,20)
 for(const q of generated.packageData.questions){
  const original=originalMap.get(q.id)
  assert.ok(original)
  assert.equal(q.content.en.stem,original.content.en.stem)
  assert.equal(q.content.en.answer,original.content.en.answer)
  assert.deepEqual(canonicalOptions(q.content.en.options),canonicalOptions(original.content.en.options))
  assert.equal(q.content.en.options['ABCD'.indexOf(q.correctOptionId)].text,original.content.en.answer)
  assert.deepEqual(q.source,original.source)
  assert.deepEqual(q.curriculum,original.curriculum)
  assert.equal(q.marks,original.marks)
  assert.equal(q.editorialCandidate.sourceQuestionSha256,SHA(JSON.stringify(original)))
  assert.equal(q.review.status,'draft')
  assert.ok(Object.values(q.review.checks).every(v=>v===false))
 }
})
test('new option sequence has balanced letters and no predictable cycle detected by existing MCQ key checker',()=>{
 const inspected=inspectMcqs(generated.packageData.questions.map(q=>({
  id:q.id,type:'mcq',correctOption:q.correctOptionId,options:q.content.en.options.map(x=>x.text)
 })))
 assert.deepEqual(inspected.findings,[])
})
test('committed derivative and review docket bytes are deterministic, parent source files are unchanged',()=>{
 assert.deepEqual(generated.packageBytes,fs.readFileSync(OUT))
 assert.deepEqual(generated.docketBytes,fs.readFileSync(DOCKET))
 assert.equal(generated.docket.revisionFileSha256,SHA(generated.packageBytes))
 assert.equal(generated.docket.items.length,20)
 assert.equal(reviewLinks.length,20)
 for(const config of FILES)assert.equal(SHA(fs.readFileSync(path.join(IN,config.file))),config.expectedSha256)
})
test('a modified source file is rejected before any candidate could be generated',()=>{
 assert.throws(()=>build(file=>{
  const buffer=fs.readFileSync(path.join(IN,file))
  if(file===FILES[0].file)return Buffer.concat([buffer,Buffer.from(' ')])
  return buffer
 }),/ORIGINAL_AUTHORING_FILE_SHA_CHANGED/)
})
test('forged review approval and unauthorized changed candidate answer are rejected',()=>{
 const badDocket=clone(generated.docket)
 badDocket.approved=1
 assert.throws(()=>verify({docketBytes:Buffer.from(JSON.stringify(badDocket))}),/UNSAFE_OR_STALE_MCQ_EDITORIAL_PACKET/)
 const bad=clone(generated.packageData)
 bad.questions[0].content.en.answer='incorrect answer'
 const body=Buffer.from(JSON.stringify(bad))
 const adjusted=clone(generated.docket)
 adjusted.revisionFileSha256=SHA(body)
 assert.throws(()=>verify({packageBytes:body,docketBytes:Buffer.from(JSON.stringify(adjusted))}),/PROPOSAL_MCQ_REVIEW_BINDING_INVALID|MCQ_OPTION_OR_ANSWER_MUTATED/)
})
test('unchanged review queue links exactly 20 Chemistry option-order proposals plus four Urdu translations without approving anything',()=>{
 const queue=buildReviewQueue(collectDocuments(),manifest,{},loadCandidates(),reviewLinks)
 assert.equal(queue.counts.questionRecords,2581)
 assert.equal(queue.counts.approved,0)
 assert.equal(queue.counts.published,0)
 assert.equal(queue.unapprovedEditorialTranslationProposals,4)
 assert.equal(queue.unapprovedMcqRevisionProposals,20)
 const linked=queue.records.filter(x=>x.editorialMcqRevisionCandidate)
 assert.equal(linked.length,20)
 assert.ok(linked.every(q=>q.type==='mcq'&&q.editorialMcqRevisionCandidate.approved===false))
 assert.ok(linked.every(q=>q.status.approved===false))
})
test('review queue rejects altered original content, duplicate MCQ proposal and forged approval',()=>{
 const candidates=reviewLinks
 const docs=collectDocuments()
 const mutated=docs.map(x=>({...x,data:clone(x.data)}))
 const file=mutated.find(x=>x.file===FILES[0].file)
 file.data.drafts.find(q=>q.id===candidates[0].questionId).content.en.answer+='changed'
 assert.throws(()=>buildReviewQueue(mutated,manifest,{},[],candidates),/CHEMISTRY_MCQ_REVISION_SOURCE_DRIFT/)
 assert.throws(()=>buildReviewQueue(docs,manifest,{},[],[candidates[0],candidates[0]]),/DUPLICATE_CHEMISTRY_MCQ_EDITORIAL_CANDIDATE/)
 const fake=clone(candidates[0]);fake.approved=true
 assert.throws(()=>buildReviewQueue(docs,manifest,{},[],[fake]),/CHEMISTRY_MCQ_REVISION_SOURCE_DRIFT/)
})
