'use strict'
const test=require('node:test'),assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto')
const {build,markdown,ANSWERS,DEFERRED_IDS,PIN}=require('../qbank/author-chemistry10-ten-safe-long-answer-candidates.cjs')
const {rubricOnlyLongAnswer}=require('../../al-siddique-backend/src/services/grade910ModelAnswerPolicy')
const ROOT=path.resolve(__dirname,'../..')
const FILE=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging/chemistry10Starter2026.json')
const bytes=fs.readFileSync(FILE),original=JSON.parse(bytes)
const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'al-siddique-backend/src/data/verifiedGrade910SourceRegistry.json')))
const sha=x=>crypto.createHash('sha256').update(x).digest('hex')
const run=(b=bytes,s=original,r=registry)=>build({bytes:b,source:s,registry:r})
test('authentic 65-candidate Chemistry X source yields 10 safe original explanations and 3 explicitly deferred source IDs',()=>{
 const d=run()
 assert.equal(sha(bytes),PIN)
 assert.equal(d.originalAuthoredResearchQuestions,65)
 assert.equal(d.originalRubricOnlyLongQuestions,13)
 assert.equal(d.newExplanatoryAnswerResearchDrafts,10)
 assert.equal(d.newFiveMarkPointProposals,50)
 assert.equal(Object.keys(ANSWERS).length,10)
 assert.deepEqual(d.originalLongQuestionIdsIntentionallyDeferred,DEFERRED_IDS)
 assert.equal(new Set(d.items.map(x=>x.questionId)).size,10)
 assert.deepEqual(d.items.map(x=>x.questionId),original.drafts.filter(q=>q.type==='long'&&!DEFERRED_IDS.includes(q.id)).map(x=>x.id))
 assert.equal(d.academicallyApproved,0)
})
test('individual original question and answer SHA remain immutable, candidate answers substantive and never auto-approved',()=>{
 const d=run(),source=new Map(original.drafts.map(x=>[x.id,x]))
 for(const x of d.items){
  const q=source.get(x.questionId)
  assert.ok(q)
  assert.equal(x.sourceQuestionSha256,sha(JSON.stringify(q)))
  assert.equal(x.sourceAnswerSha256,sha(q.content.en.answer))
  assert.equal(x.sourceFileSha256,PIN)
  assert.equal(x.catalogSourceId,original.sourceRecordId)
  assert.equal(x.claimedSourcePdfSha256,original.sourcePdfSha256)
  assert.equal(x.chapterNo,q.chapter.number)
  assert.equal(x.topicId,q.topicId)
  assert.equal(x.marks,5)
  assert.ok(x.proposedIndependentEnglishExplanation.length>=250)
  assert.notEqual(x.proposedIndependentEnglishExplanation,q.content.en.answer)
  assert.equal(rubricOnlyLongAnswer('long',x.proposedIndependentEnglishExplanation),false)
  assert.equal(x.proposedDistinctMarkingPoints.length,5)
  assert.equal(new Set(x.proposedDistinctMarkingPoints).size,5)
  assert.equal(x.schoolAdoptedEditionSessionVerified,false)
  assert.equal(x.originalPrintedExercisePageVerified,false)
  assert.equal(x.qualifiedIndependentSubjectReviewed,false)
  assert.equal(x.urduEquivalenceReviewed,false)
  assert.equal(x.independentReviewerId,null)
  assert.equal(x.approvedRevisionId,null)
  assert.equal(x.academicallyApproved,false)
  assert.equal(x.verifiedPublished,false)
 }
})
test('electrochemistry draft separates electrode redox roles from polarity to prevent galvanic/electrolytic confusion',()=>{
 const d=run(),m=new Map(d.items.map(x=>[x.questionId,x.proposedIndependentEnglishExplanation]))
 const e=m.get('X-CHEM-C16-L01')
 assert.match(e,/anode is defined as the electrode at which oxidation occurs/)
 assert.match(e,/cathode as the electrode at which reduction occurs/)
 assert.match(e,/polarities.*not the same/)
 assert.match(m.get('X-CHEM-C15-L01'),/limiting reactant/)
 assert.match(m.get('X-CHEM-C21-L01'),/CH2 unit/)
 assert.match(m.get('X-CHEM-C25-L01'),/not all lipids are repeating polymers/)
})
test('deferred chemistry lab procedures are excluded and require human safety/source review',()=>{
 const d=run(),ids=new Set(d.items.map(x=>x.questionId)),m=markdown(d)
 assert.deepEqual(d.originalLongQuestionIdsIntentionallyDeferred,['X-CHEM-C18-L01','X-CHEM-C23-L01','X-CHEM-C24-L01'])
 for(const id of DEFERRED_IDS){assert.equal(ids.has(id),false);assert.ok(m.includes(id))}
 assert.match(m,/qualified safety\/academic review/)
 assert.doesNotMatch(JSON.stringify(d.items),/ethanol preparation procedure|pour acid|mix concentrated acid/i)
})
test('tampered long original answer or unrelated MCQ fails whole pinned source file digest',()=>{
 for(const id of ['X-CHEM-C16-L01','X-CHEM-C14-M01']){
  const x=structuredClone(original),q=x.drafts.find(q=>q.id===id)
  assert.ok(q)
  q.content.en.answer='Changed unapproved original answer'
  assert.throws(()=>run(Buffer.from(JSON.stringify(x)),x),/CHEM10_SOURCE_SHA_CHANGED/)
 }
})
test('original unchanged source bytes plus forged in-memory data fail closed',()=>{
 const x=structuredClone(original)
 x.drafts[0].content.en.answer='Forged data'
 assert.throws(()=>run(bytes,x),/CHEM10_SOURCE_SHA_CHANGED/)
})
test('catalog PDF identity, medium, 2026 edition and no academic approval are exact claims, not school certification',()=>{
 for(const mutate of [x=>{x.pdfSha256='0'.repeat(64)},x=>{x.medium='Urdu'},x=>{x.edition='school approved 2026'},x=>{x.academicApproval=true}]){
  const r=structuredClone(registry)
  mutate(r.entries.find(x=>x.recordId===original.sourceRecordId))
  assert.throws(()=>run(bytes,original,r),/CHEM10_UNVERIFIED_CATALOG_IDENTITY_DRIFT/)
 }
})
test('faculty packet explicitly labels original 13 rubrics and only ten safe answer drafts',()=>{
 const d=run(),m=markdown(d)
 assert.match(m,/ten source-bound conceptual explanatory draft answers/i)
 assert.match(m,/all 13 long answers previously contained rubric-only text/)
 assert.match(m,/Ten source-bound non-procedural explanations/)
 assert.match(m,/textbook adoption, printed exercise page and relevant actual examination year are NOT independently verified/)
 assert.match(m,/Paper Studio verified selector remains empty/)
})
test('no publication or fabricated academic reviewer or original curriculum claim in new packet',()=>{
 const d=run()
 assert.equal(d.humanSchoolSourceVerified,0)
 assert.equal(d.qualifiedHumanAcademicReviewed,0)
 assert.equal(d.verifiedPublished,0)
 assert.equal(d.academicallyApproved,0)
 assert.equal(d.sourceCatalogMediumClaim,'English')
 assert.equal(d.sourceCatalogEditionClaim,'2026')
 assert.ok(d.items.every(x=>x.reviewStatus==='RESEARCH_DRAFT_REQUIRES_CHEMISTRY_X_SCHOOL_ADOPTION_AND_INDEPENDENT_REVIEW'))
})
