'use strict'
const test=require('node:test'),assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto')
const {build,markdown,ANSWERS,ORIGINAL_SHA}=require('../qbank/author-computer10-eight-long-answers.cjs')
const ROOT=path.resolve(__dirname,'../..')
const FILE=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging/computer10Starter2026.json')
const bytes=fs.readFileSync(FILE),source=JSON.parse(bytes)
const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'al-siddique-backend/src/data/verifiedGrade910SourceRegistry.json')))
const sha=b=>crypto.createHash('sha256').update(b).digest('hex')
const run=(b=bytes,s=source,r=registry)=>build({bytes:b,source:s,registry:r})
test('real 40-candidate Computer X file maps all and only eight long-answer IDs to new research answers',()=>{
 const d=run()
 assert.equal(sha(bytes),ORIGINAL_SHA)
 assert.equal(d.originalCandidateQuestionCount,40)
 assert.equal(d.originalRubricOnlyLongQuestionCount,8)
 assert.equal(d.newSeparateExplanatoryAnswerProposals,8)
 assert.equal(d.newSeparateMarkingCriterionProposals,40)
 assert.deepEqual(d.items.map(q=>q.questionId),source.drafts.filter(x=>x.type==='long').map(x=>x.id))
 assert.equal(new Set(d.items.map(q=>q.questionId)).size,8)
 assert.equal(d.academicApprovalCount,0)
 assert.equal(d.publishedCount,0)
})
test('each explanation differs from original grading direction and carries five distinct assessable marking points',()=>{
 const d=run(),ids=new Map(source.drafts.map(q=>[q.id,q]))
 assert.equal(Object.keys(ANSWERS).length,8)
 for(const x of d.items){
  const q=ids.get(x.questionId)
  assert.ok(q)
  assert.equal(x.originalQuestionSha256,sha(JSON.stringify(q)))
  assert.equal(x.originalAnswerSha256,sha(q.content.en.answer))
  assert.equal(x.originalSourceFileSha256,ORIGINAL_SHA)
  assert.equal(x.chapterNo,q.chapter.number)
  assert.equal(x.topicId,q.topicId)
  assert.equal(x.marks,5)
  assert.ok(x.proposedOriginalEnglishExplanatoryAnswer.length>=230)
  assert.notEqual(x.proposedOriginalEnglishExplanatoryAnswer,q.content.en.answer)
  assert.ok(!/^\s*award marks?/i.test(x.proposedOriginalEnglishExplanatoryAnswer))
  assert.equal(x.proposedSeparateMarkingCriteria.length,5)
  assert.equal(new Set(x.proposedSeparateMarkingCriteria).size,5)
  assert.equal(x.subjectTeacherCorrectnessVerified,false)
  assert.equal(x.schoolTextbookEditionAndPageVerified,false)
  assert.equal(x.englishUrduEquivalenceVerified,false)
  assert.equal(x.independentReviewerId,null)
  assert.equal(x.approvedRevisionId,null)
  assert.equal(x.academicApproved,false)
  assert.equal(x.published,false)
 }
})
test('computer science explanations distinguish system calls and drivers, score thresholds and privacy',()=>{
 const d=run(),a=new Map(d.items.map(x=>[x.questionId,x.proposedOriginalEnglishExplanatoryAnswer]))
 assert.match(a.get('X-COMP-U01-L01'),/system calls/i)
 assert.match(a.get('X-COMP-U01-L01'),/device drivers/i)
 assert.match(a.get('X-COMP-U04-L01'),/illustrative rather than an ASSPS grading policy/)
 assert.match(a.get('X-COMP-U05-L01'),/authorized educational purpose/)
 assert.match(a.get('X-COMP-U06-L01'),/training data/)
 assert.match(a.get('X-COMP-U07-L01'),/human responsibility/)
})
test('tampered original long answer and unrelated short answer cannot inherit a stale original review snapshot',()=>{
 for(const id of ['X-COMP-U01-L01','X-COMP-U01-S01']){
  const changed=structuredClone(source),q=changed.drafts.find(q=>q.id===id)
  assert.ok(q,id)
  q.content.en.answer='Unapproved changed content'
  assert.throws(()=>run(Buffer.from(JSON.stringify(changed)),changed),/COMP10_ORIGINAL_FILE_SHA_CHANGED/)
 }
})
test('in-memory original source disagreement is rejected even when pinned original file bytes are supplied',()=>{
 const changed=structuredClone(source)
 changed.drafts[0].content.en.answer='Different in memory'
 assert.throws(()=>run(bytes,changed),/COMP10_ORIGINAL_FILE_SHA_CHANGED/)
})
test('canonical Computer X source PDF SHA must match the immutable registry identity',()=>{
 const r=structuredClone(registry),entry=r.entries.find(x=>x.recordId===source.sourceRecordId)
 assert.ok(entry)
 entry.pdfSha256='0'.repeat(64)
 assert.throws(()=>run(bytes,source,r),/COMP10_SOURCE_CATALOG_IDENTITY_CHANGED/)
})
test('unknown canonical textbook registry ID fails closed, not auto-approved',()=>{
 const r=structuredClone(registry)
 r.entries=r.entries.filter(x=>x.recordId!==source.sourceRecordId)
 assert.throws(()=>run(bytes,source,r),/COMP10_SOURCE_CATALOG_IDENTITY_CHANGED/)
})
test('faculty-readable packet correctly declares zero human review and publication HOLD',()=>{
 const d=run(),m=markdown(d)
 assert.match(m,/eight independently authored long-answer drafts/)
 assert.match(m,/Independent source\/page verification: 0/)
 assert.match(m,/Academically approved: 0/)
 assert.match(m,/verified picker empty/)
 assert.equal(d.realTeacherReviewCount,0)
 assert.equal(d.items.every(x=>x.originalAnswerUnmodified===true && x.academicApproved===false && x.published===false),true)
})
test('output includes no new production-ready or approved question identity',()=>{
 const d=run()
 assert.ok(d.items.every(x=>x.status==='INDEPENDENT_AUTHORING_DRAFT_FOR_COMPUTER_X_TEACHER_REVIEW'))
 assert.equal(d.sourcePageVerifiedCount,0)
 assert.equal(d.publishedCount,0)
 assert.equal(d.items.length,source.drafts.filter(x=>x.type==='long').length)
})
