'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const {analyze}=require('../qbank/build-grade910-adoption-evidence-docket.cjs')
const ROOT=path.resolve(__dirname,'../..')
const STARTER=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging')
const load=name=>JSON.parse(fs.readFileSync(path.join(ROOT,name)))
const registry=load('al-siddique-backend/src/data/verifiedGrade910SourceRegistry.json')
const adoptions=load('al-siddique-backend/src/data/asspsGrade910SchoolAdoptions.json')
const physical=load('al-siddique-backend/src/data/asspsGrade910PhysicalPageEvidence.json')
const docs=fs.readdirSync(STARTER).filter(name=>name.endsWith('Starter2026.json')).sort().map(filename=>({filename,data:JSON.parse(fs.readFileSync(path.join(STARTER,filename))),fileSha256:'a'.repeat(64)}))
const clone=v=>JSON.parse(JSON.stringify(v))
const invoke=(overrides={})=>analyze({registry,adoptions,physical,documents:docs,...overrides})
test('original 55 starter files reconcile complete per-question PDF source identities without approving any questions',()=>{
 const d=invoke()
 assert.equal(d.input.starterFiles,55)
 assert.equal(d.totals.starterDraftQuestions,2096)
 assert.equal(d.totals.distinctQuestionIds,2096)
 assert.equal(d.totals.referencedSourceRecords,55)
 assert.equal(d.totals.approved,0)
 assert.equal(d.totals.humanSourceVerified,0)
 assert.equal(d.totals.publishedVerified,0)
 assert.equal(d.input.schoolAdoptionCertified,false)
 assert.equal(d.input.physicalPageCertified,false)
 assert.equal(d.cohorts.reduce((sum,item)=>sum+item.stagedDrafts,0),2096)
 assert.ok(d.cohorts.every(s=>s.verifiedQuestionCount===0&&s.approvedQuestionCount===0))
})
test('edition, source grade and medium blockers are counted distinctly and never summed as unique unreviewed questions',()=>{
 const d=invoke()
 assert.equal(d.totals.nonExplicitEditionDrafts,877)
 assert.equal(d.totals.draftEditionSourceDisagreements,433)
 assert.equal(d.totals.unresolvedSourceGradeDrafts,70)
 assert.equal(d.totals.unresolvedSourceMediumDrafts,310)
 assert.match(d.caveat,/Overlapping blocker counts are not additive/)
 const grammar=d.cohorts.find(x=>x.sourceRecordId==='pectaa-catalog-107')
 assert.equal(grammar.stagedDrafts,70)
 assert.equal(grammar.sourceGradeNeedsResolution,true)
 const biology=d.cohorts.find(x=>x.sourceRecordId==='pectaa-catalog-009')
 assert.equal(biology.stagedDrafts,66)
 assert.equal(biology.editionLabelNeedsVerification,false)
 assert.ok(biology.blockers.includes('SCHOOL_BOOK_ADOPTION_NOT_CERTIFIED'))
})
test('dual-medium source file is attributed to two per-question actual source IDs and not falsely labeled missing',()=>{
 const d=invoke()
 const a=d.cohorts.find(x=>x.sourceRecordId==='pectaa-catalog-045')
 const b=d.cohorts.find(x=>x.sourceRecordId==='pectaa-catalog-046')
 assert.ok(a&&b)
 assert.equal(a.stagedDrafts+b.stagedDrafts,64)
 assert.ok(a.files.some(x=>x.filename==='physicsTech9DualStarter2026.json'))
 assert.ok(b.files.some(x=>x.filename==='physicsTech9DualStarter2026.json'))
})
test('tampered per-question source PDF hash is refused before rendering a misleading evidence docket',()=>{
 const one=clone(docs[0])
 one.data.drafts[0].source.pdfSha256='0'.repeat(64)
 assert.throws(()=>invoke({documents:[one]}),/ADOPTION_DOCKET_PDF_HASH_DRIFT/)
})
test('unknown source IDs and duplicated question identifiers fail closed',()=>{
 const one=clone(docs[0]);one.data.drafts[0].source.catalogRecordId='NO-SUCH-TEXTBOOK'
 assert.throws(()=>invoke({documents:[one]}),/ADOPTION_DOCKET_UNKNOWN_SOURCE/)
 const two=clone(docs[0]);two.data.drafts[1].id=two.data.drafts[0].id
 assert.throws(()=>invoke({documents:[two]}),/ADOPTION_DOCKET_DUPLICATE_QUESTION_ID/)
})
test('published or auto-import-enabled research file cannot enter this evidence-only intake',()=>{
 for(const flag of ['publicationAllowed','liveImportAllowed']){
  const file=clone(docs[0]);file.data[flag]=true
  assert.throws(()=>invoke({documents:[file]}),/ADOPTION_DOCKET_UNSAFE_PUBLICATION_STATUS/)
 }
})
test('same inputs yield a reproducible, stable source-cohort ordering without marking anything approved',()=>{
 const a=invoke()
 const b=invoke({documents:docs.slice().reverse()})
 assert.deepEqual(a.totals,b.totals)
 assert.deepEqual(a.cohorts.map(x=>[x.sourceRecordId,x.stagedDrafts]),b.cohorts.map(x=>[x.sourceRecordId,x.stagedDrafts]))
 assert.ok(a.cohorts.every(x=>x.blockers.includes('INDEPENDENT_HUMAN_ANSWER_AND_TEXTBOOK_REVIEW_REQUIRED')))
})
test('official PDF registry does not become an adoption or physical-page certificate by itself',()=>{
 const d=invoke()
 assert.ok(d.cohorts.every(x=>x.blockers.includes('SCHOOL_BOOK_ADOPTION_NOT_CERTIFIED')&&
    x.blockers.includes('PHYSICAL_PRINTED_PDF_PAGE_NOT_CERTIFIED')))
 assert.equal(adoptions.schoolBookAndExamYearApplicabilityCertified,false)
 assert.equal(physical.academicPageEvidenceCertified,false)
})
