'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const crypto=require('node:crypto')
const {buildReviewQueue}=require('../qbank/build-grade910-review-triage.cjs')
const {collectDocuments}=require('../qbank/audit-authoring-crossfile-qa.cjs')
const ROOT=path.resolve(__dirname,'../..')
const STAGING=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging')
const source=JSON.parse(fs.readFileSync(path.join(STAGING,'officialSourceManifest.json'),'utf8'))
const mcq=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/question-bank/ASSPS_GRADE910_MCQ_AUTHORING_QA_20261008.json'),'utf8'))
const docs=collectDocuments()
const audit=buildReviewQueue(docs,source,mcq)
const sha=v=>crypto.createHash('sha256').update(v).digest('hex')
test('review queue covers exactly the unique source-authoring 2581 questions with no derivative duplicates',()=>{
 assert.equal(audit.counts.questionRecords,2581)
 assert.equal(audit.counts.stableQuestionIds,2581)
 assert.equal(audit.counts.originalAuthoringFiles,73)
 assert.equal(audit.counts.collisionIds,0)
 assert.equal(audit.counts.sourceVerified,0)
 assert.equal(audit.counts.independentlyReviewed,0)
 assert.equal(audit.counts.approved,0)
 assert.equal(audit.counts.published,0)
 assert.equal(audit.records.length,2581)
})
test('each review item links to current exact draft SHA, no serialized stem, options or answer text',()=>{
 const indexed=new Map()
 for(const {file,data} of docs)for(const q of [...(data?.drafts||[]),...(data?.items||[])])
  if(q?.id)indexed.set(q.id,{q,file})
 for(const row of audit.records){
  const expected=indexed.get(row.questionId)
  assert.ok(expected, row.questionId)
  assert.equal(row.sourceFile,expected.file)
  assert.equal(row.questionContentSha256,sha(JSON.stringify(expected.q)))
  assert.match(row.questionContentSha256,/^[0-9a-f]{64}$/)
  assert.equal(Object.hasOwn(row,'questionText'),false)
  assert.equal(Object.hasOwn(row,'options'),false)
  assert.equal(Object.hasOwn(row,'answer'),false)
  assert.equal(row.evidenceTier,'RESEARCH_CANDIDATE_ONLY')
  assert.equal(row.status.approved,false)
  assert.equal(row.status.published,false)
 }
})
test('source hash metadata alone never proves source image page or school adoption',()=>{
 assert.equal(audit.blockerCounts.SCHOOL_APPROVED_EDITION_AND_EXAM_YEAR_UNCONFIRMED,2581)
 assert.equal(audit.blockerCounts.INDEPENDENT_ACADEMIC_REVIEW_MISSING,2581)
 assert.equal(audit.blockerCounts.SOURCE_PAGE_CLAIM_MISSING,1188)
 assert.equal(audit.blockerCounts.SOURCE_PAGE_CLAIM_NOT_PHYSICALLY_VERIFIED,1393)
 assert.equal(audit.blockerCounts.TEXTBOOK_EDITION_LABEL_UNRESOLVED,921)
 assert.equal(audit.blockerCounts.CHAPTER_MAPPING_UNRESOLVED,44)
 assert.equal(audit.blockerCounts.SOURCE_FILE_MCQ_KEY_PATTERN_EDITORIAL_REVIEW,743)
 assert.equal(audit.schoolApprovedBookEditionEvidencePresent,false)
 assert.equal(audit.sourceChapterAndExerciseIndependentVerification,false)
})
test('different language cohorts preserved without asserting translation accuracy',()=>{
 assert.equal(audit.byMedium.english,1562)
 assert.equal(audit.byMedium.urdu,971)
 assert.equal(audit.byMedium.dual,48)
 assert.equal(audit.blockerCounts.BILINGUAL_EQUIVALENCE_INDEPENDENT_CHECK_MISSING,54)
})
test('revision change makes a new SHA and never inherits pending review signoff',()=>{
 const q={id:'T001',type:'mcq',questionText:'Sample?',options:['A','B','C','D'],correctOptionId:'B',
  source:{catalogRecordId:'s',pdfSha256:'a'.repeat(64)}}
 const manifest={entries:[{recordId:'s',grade:9,subject:'Science',medium:'English',pdfSha256:'a'.repeat(64)}]}
 const x=buildReviewQueue([{file:'source.json',data:{drafts:[q]}}],manifest)
 const edited={...q,options:['B','A','C','D'],correctOptionId:'A',review:{status:'approved'}}
 const y=buildReviewQueue([{file:'source.json',data:{drafts:[edited]}}],manifest)
 assert.notEqual(x.records[0].questionContentSha256,y.records[0].questionContentSha256)
 assert.deepEqual(y.records[0].status,{sourceVerified:false,independentlyReviewed:false,approved:false,published:false})
 assert.equal(y.records[0].reviewerId,null)
})
test('two files sharing a permanent ID are explicitly flagged as collision',()=>{
 const q={id:'DUP',questionText:'Question?',type:'short'}
 const x=buildReviewQueue([{file:'a.json',data:{drafts:[q]}},{file:'b.json',data:{drafts:[q]}}],{entries:[]})
 assert.equal(x.counts.questionRecords,1)
 assert.equal(x.counts.collisionIds,1)
 assert.deepEqual(x.collisions,[{id:'DUP',file:'b.json'}])
 assert.ok(x.records[0].blockers.includes('OFFICIAL_SOURCE_HASH_OR_IDENTITY_UNVERIFIED'))
})
