const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const root=path.resolve(__dirname,'../..')
const read=n=>JSON.parse(fs.readFileSync(path.join(root,'docs/question-bank/reports-20261002',n),'utf8'))

test('Grade IX-X readiness seal remains truthful and fail-closed',()=>{
  const gaps=read('28_GRADE910_ACADEMIC_READINESS_GAPS_20261008.json')
  const text=read('29_GRADE910_PDF_TEXT_LAYER_CLASSIFICATION_20261008.json')
  const maps=read('30_GRADE910_TEXT_LAYER_CANDIDATE_MAPS_20261008.json')
  const seal=read('31_GRADE910_READINESS_COMPLETION_SEAL_20261008.json')
  assert.equal(gaps.live.discoveredQuestions,2303)
  assert.equal(gaps.live.approvedQuestions,0)
  assert.equal(gaps.live.mcqAnswerKeys.total,773)
  assert.equal(gaps.live.mcqAnswerKeys.editorialReviewFlag,false)
  assert.equal(text.summary.hashAttested,110)
  assert.equal(text.summary.integrityVerified,110)
  assert.equal(text.summary.integrityFailures,0)
  assert.equal(text.summary.sourceUnresolved,1)
  assert.equal(text.summary.textLayerGood+text.summary.textLayerPartial+text.summary.imageHeavy,110)
  assert.equal(maps.summary.eligibleRecords,17)
  assert.equal(maps.summary.totalCandidates,547)
  assert.equal(maps.summary.verifiedChapterMaps,0)
  assert.equal(maps.summary.verifiedExerciseIndices,0)
  assert.equal(maps.summary.academicApprovalGranted,false)
  assert.equal(seal.liveProvisionalBank.approved,0)
  assert.equal(seal.academicReadiness.academicReady,false)
  assert.equal(seal.academicReadiness.publicationReady,false)
  assert.deepEqual(seal.sourceEvidence.sourceUnresolvedRecordIds,['pectaa-catalog-037'])
  assert.equal(seal.completionDecision,'AUTOMATION_AND_ENGINEERING_READINESS_COMPLETE_ACADEMIC_APPROVAL_BLOCKED')
})
