'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const {BATCHES,audit,ops,hasExactResultMarker,baselineCandidate}=require('../qbank/audit-core-grade910-numerical-answers.cjs')
const STAGING=path.resolve(__dirname,'../../al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging')
const BASELINE=require('../qbank/grade910-core-numerical-golden-sha-20261008.json')
const make=(file)=>structuredClone(JSON.parse(fs.readFileSync(path.join(STAGING,file),'utf8')))
test('exactly 43 original numericals in five IX/X English/Urdu batches recompute and match stored answers',()=>{
 const r=audit()
 assert.equal(r.questions,43)
 assert.equal(r.passed,43)
 assert.equal(r.failed,0)
 assert.equal(r.batches,5)
 assert.equal(r.results.length,43)
 assert.deepEqual([r.sourceVerified,r.humanReviewed,r.approved,r.published],[0,0,0,0])
 for(const row of r.results)assert.equal(row.academicallyApproved,false)
})
test('golden revision ledger hashes remain frozen and every source numerical is accounted for exactly once',()=>{
 const expected=Object.values(BATCHES).flatMap(v=>v.map(([id])=>id))
 assert.equal(new Set(expected).size,43)
 assert.equal(BASELINE.items.length,43)
 assert.deepEqual(new Set(BASELINE.items.map(x=>x.questionId)),new Set(expected))
 assert.deepEqual(baselineCandidate(),BASELINE)
 for(const [file,list] of Object.entries(BATCHES)){
  const draft=make(file)
  assert.deepEqual(new Set(list.map(row=>row[0])),new Set(draft.drafts.filter(q=>q.type==='numerical').map(q=>q.id)))
 }
})
test('edited question stem changes hash and cannot inherit mechanical review from old revision',()=>{
 const file='physics9EnglishStarter2026.json',doc=make(file)
 doc.drafts.find(q=>q.id==='IX-PHY-2025-C02-N01').content.en.stem='Modified velocity problem'
 const r=audit({documents:{[file]:doc}})
 assert.equal(r.passed,42)
 const one=r.results.find(x=>x.questionId==='IX-PHY-2025-C02-N01')
 assert.equal(one.baselineContentMatches,false)
 assert.equal(one.mathematicalRecomputationPass,true)
 assert.equal(one.passed,false)
})
test('corrupt Urdu numerical answer is rejected even if the fixed formula remains mathematically right',()=>{
 const file='mathematics9UrduStarter2026.json',doc=make(file)
 doc.drafts.find(q=>q.id==='IX-MATH-UR-C06-N01').content.ur.answer='وتر=14 cm۔'
 const r=audit({documents:{[file]:doc}})
 assert.equal(r.passed,42)
 const one=r.results.find(x=>x.questionId==='IX-MATH-UR-C06-N01')
 assert.equal(one.storedAnswerTokenCrosscheckPass,false)
 assert.equal(one.baselineContentMatches,false)
})
test('numeric marker must not match a larger number accidentally',()=>{
 assert.equal(hasExactResultMarker('v=113 m/s','13m/s'),false)
 assert.equal(hasExactResultMarker('v=13 m/s','13m/s'),true)
 assert.equal(hasExactResultMarker('3+(-1)=20','=2'),false)
 assert.equal(hasExactResultMarker('3+(-1)=2.','=2'),true)
 assert.equal(hasExactResultMarker('1300 K','300K'),false)
 assert.equal(hasExactResultMarker('300 K','300K'),true)
})
test('new numerical rows must not be ignored and baseline never silently overwrites',()=>{
 const file='physics10Starter2026.json',doc=make(file)
 doc.drafts.push({...doc.drafts.find(q=>q.type==='numerical'),id:'X-PHY-UNREVIEWED-EXTRA'})
 assert.throws(()=>audit({documents:{[file]:doc}}),/UNACCOUNTED_NUMERICAL_DRAFT/)
})
test('individual calculators cover independently recomputed physics and grade IX maths',()=>{
 assert.equal(ops.waveSpeed(50,2),100)
 assert.equal(ops.echoDistance(340,.4),68)
 assert.equal(ops.halfLife(800,3),100)
 assert.equal(ops.union(18,15,6),27)
 assert.equal(ops.systemX(10,2),6)
 assert.equal(ops.factorIdentity(3,4,7,12),1)
 assert.equal(ops.factorIdentity(3,5,7,12),0)
})
