const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '../..')
const read = rel => fs.readFileSync(path.join(repoRoot, rel), 'utf8')

test('Paper Vault and immutable journal use one restricted runtime boundary', () => {
  const route = read('al-siddique-backend/src/routes/paperRoute.js')
  const runtime = read('al-siddique-backend/src/services/papers/paperVaultRuntimeRole.js')
  const revision = read('al-siddique-backend/src/services/papers/paperVaultRevisionV6D.js')
  assert.match(runtime, /SET LOCAL ROLE apex_paper_runtime/)
  assert.match(runtime, /set_config\('app\.tenant_id'/)
  assert.match(runtime, /async function withPaperVaultRuntime/)
  assert.match(route, /paperVaultRuntimeRole/)
  assert.ok((route.match(/withPaperVaultRuntime\(schoolId/g) || []).length >= 2)
  assert.match(revision, /paperVaultRuntimeRole/)
  assert.ok((revision.match(/await applyPaperVaultRuntimeContext\(client,schoolId\)/g) || []).length >= 3)
  assert.ok((revision.match(/withPaperVaultRuntime\(schoolId/g) || []).length >= 2)
  assert.doesNotMatch(revision, /pool\.query\(migration\)/)
})

test('Paper Vault migration grants only its table and sequence to the runtime role', () => {
  const migration = read('al-siddique-backend/migrations/020_paper_vault_schema.js')
  assert.match(migration, /GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE paper_vault TO apex_paper_runtime/)
  assert.match(migration, /GRANT USAGE, SELECT ON SEQUENCE paper_vault_id_seq TO apex_paper_runtime/)
  assert.match(migration, /GRANT SELECT, INSERT ON TABLE paper_vault_revision_history TO apex_paper_runtime/)
  assert.match(migration, /paper_vault_history_school_paper_fk/)
  assert.match(migration, /FOREIGN KEY \(school_id, paper_id\)/)
  assert.match(migration, /GRANT SELECT ON TABLE teacher_class_assignments TO apex_paper_runtime/)
})

test('Paper Vault participates in strict tenant RLS coverage', () => {
  const rls = read('al-siddique-backend/src/config/migrations/005_rls_policies.js')
  assert.match(rls, /'paper_vault'/)
  assert.match(rls, /'paper_vault', 'paper_vault_revision_history'/)
  assert.match(rls, /'paper_vault', 'paper_vault_revision_history', 'teacher_class_assignments'/)
  assert.ok(rls.indexOf("'paper_vault', 'paper_vault_revision_history'") > rls.indexOf('const strictTables'))
  assert.match(rls, /ALTER TABLE \$\{table\} FORCE ROW LEVEL SECURITY/)
})
