'use strict'
const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const src=path.resolve(__dirname,'../../al-siddique-backend/src')
const migration=fs.readFileSync(path.join(src,'config/migrations/011_fee_payment_modes_v1.js'),'utf8')
const feeRoutes=fs.readFileSync(path.join(src,'routes/feeRoutes.js'),'utf8')
const migrate=fs.readFileSync(path.join(src,'config/migrate.js'),'utf8')
const frontend=fs.readFileSync(path.resolve(__dirname,'../../al-siddique-frontend/src/Modules/fees/FeeModule.jsx'),'utf8')
test('fee migration expands database constraint to all backend-allowed payment modes',()=>{
 const match=feeRoutes.match(/const allowedModes = new Set\(\[([^\]]+)\]\)/)
 assert.ok(match,'route must expose explicit allowlist')
 const values=[...match[1].matchAll(/'([a-z]+)'/g)].map(x=>x[1])
 assert.deepEqual(values.sort(),['cash','online','bank','jazzcash','easypaisa','card','other'].sort())
 for(const mode of values) assert.match(migration,new RegExp("'"+mode+"'"))
 assert.match(migrate,/migrations\/011_fee_payment_modes_v1/)
 assert.match(migrate,/await feePaymentModesMigration\.up\(\)/)
})
test('bank option remains usable from teacher fee form and is never mapped silently',()=>{
 assert.match(frontend,/<option value="bank">Bank<\/option>/)
 assert.match(feeRoutes,/payment_mode = \$2/)
 assert.match(feeRoutes,/payment_mode, discount_snapshot, payment_note, recorded_by/)
})
