'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const crypto=require('node:crypto')
const {build,markdown,ANSWERS,LOCKED_SHA}=require('../qbank/author-physics10-long-model-answer-candidates.cjs')
const ROOT=path.resolve(__dirname,'../..')
const src=path.join(ROOT,'al-siddique-frontend/src/Modules/Paper-Generator/seed-data/grade9-10-staging/physics10Starter2026.json')
const bytes=fs.readFileSync(src),source=JSON.parse(bytes)
const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'al-siddique-backend/src/data/verifiedGrade910SourceRegistry.json')))
const hash=x=>crypto.createHash('sha256').update(x).digest('hex')
const run=(b=bytes,s=source,r=registry)=>build({bytes:b,source:s,registry:r})
test('exact authentic Grade X Physics 60-question corpus yields all 5 original five-mark long model-answer proposals',()=>{
 const d=run()
 assert.equal(hash(bytes),LOCKED_SHA)
 assert.equal(d.originalQuestions,60)
 assert.equal(d.originalLongRubricQuestions,5)
 assert.equal(d.newAnswerDrafts,5)
 assert.equal(d.newSeparateMarkingPointDrafts,25)
 assert.deepEqual(d.items.map(x=>x.questionId),source.drafts.filter(x=>x.type==='long').map(x=>x.id))
 assert.equal(d.approved,0)
 assert.equal(d.independentlyReviewed,0)
 assert.equal(d.published,0)
})
test('five explanatory Physics answers do not copy the original rubric and maintain five separate marking criteria',()=>{
 const d=run()
 for(const x of d.items){
  const original=source.drafts.find(q=>q.id===x.questionId)
  assert.equal(x.marks,5)
  assert.equal(x.chapterNo,original.chapter.number)
  assert.equal(x.topicId,original.topicId)
  assert.ok(x.proposedEnglishModelAnswer.length>=180)
  assert.notEqual(x.proposedEnglishModelAnswer,original.content.en.answer)
  assert.equal(x.proposedSeparateMarkingPoints.length,5)
  assert.equal(new Set(x.proposedSeparateMarkingPoints).size,5)
  assert.equal(x.originalQuestionSha256,hash(JSON.stringify(original)))
  assert.equal(x.originalAnswerSha256,hash(original.content.en.answer))
  assert.equal(x.sourceFileSha256,LOCKED_SHA)
  assert.equal(x.approved,false)
  assert.equal(x.published,false)
  assert.equal(x.independentReviewerId,null)
  assert.equal(x.schoolEditionAndPageVerified,false)
  assert.equal(x.languageEquivalenceReviewed,false)
 }
 assert.equal(Object.keys(ANSWERS).length,5)
})
test('Physics X motor answer preserves the current-direction torque principle and satellite answer explains orbit',()=>{
 const d=run()
 const motor=d.items.find(x=>x.questionId==='X-PHY-C17-L01')
 const orbit=d.items.find(x=>x.questionId==='X-PHY-C21-L01')
 assert.match(motor.proposedEnglishModelAnswer,/split-ring commutator/i)
 assert.match(motor.proposedEnglishModelAnswer,/half-turn/i)
 assert.match(orbit.proposedEnglishModelAnswer,/inward acceleration/)
 assert.match(orbit.proposedEnglishModelAnswer,/gravity/i)
})
test('change in a flagged or unrelated original authored answer makes entire batch snapshot stale',()=>{
 for(const id of ['X-PHY-C11-L01','X-PHY-C10-S01']){
  const changed=structuredClone(source)
  const q=changed.drafts.find(q=>q.id===id)
  assert.ok(q)
  q.content.en.answer='Altered after originating from the exact source file'
  assert.throws(()=>run(Buffer.from(JSON.stringify(changed)),changed),/PHY10_SOURCE_REVISION_DRIFT/)
 }
})
test('forged in-memory question without identical pinned original JSON bytes fails closed',()=>{
 const changed=structuredClone(source)
 changed.drafts[0].content.en.answer='Not source-verified'
 assert.throws(()=>run(bytes,changed),/PHY10_SOURCE_REVISION_DRIFT/)
})
test('canonical source PDF identity must agree with original school-independent registry record',()=>{
 const changed=structuredClone(registry)
 const row=changed.entries.find(x=>x.recordId===source.sourceRecordId)
 row.pdfSha256='0'.repeat(64)
 assert.throws(()=>run(bytes,source,changed),/PHY10_SOURCE_REGISTRY_DRIFT/)
})
test('reproducible faculty packet never grants school textbook or answer reviewer approval',()=>{
 const d=run(),md=markdown(d)
 assert.equal(d.items.every(x=>x.originalQuestionAndAnswerUnmodified&&x.independentlySubjectReviewed===false),true)
 assert.ok(md.includes('Teacher reviewed 0'))
 assert.ok(md.includes('SaaS Core production certification HOLD'))
 assert.equal(d.items.every(x=>x.approvedRevisionId===null),true)
})
test('no original source scientific answer is silently relabeled as an approved paper answer',()=>{
 const d=run()
 assert.ok(d.items.every(x=>x.status==='ORIGINAL_MODEL_ANSWER_PROPOSAL_AWAITING_INDEPENDENT_PHYSICS_REVIEW'))
 assert.ok(d.items.every(x=>x.originalAnswerSha256.length===64))
 assert.ok(!d.items.some(x=>x.approved||x.published))
})
