const test=require('node:test'),assert=require('node:assert/strict')
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto')
const {verifyCachedPdf}=require('../qbank/verify-cached-catalog-pdf.cjs')
test('catalog source attestation requires exact PDF signature and immutable digest',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'assps-catalog-pdf-'))
 t.after(()=>fs.rmSync(dir,{recursive:true,force:true}))
 const pdf=path.join(dir,'source.pdf'),payload=Buffer.from('%PDF-'+ 'example'.repeat(400))
 fs.writeFileSync(pdf,payload)
 const digest=crypto.createHash('sha256').update(payload).digest('hex')
 const entry=new Map([['catalog-9',{pdfSha256:digest,grade:9,subject:'Biology',medium:'English'}]])
 const verified=await verifyCachedPdf('catalog-9',pdf,entry)
 assert.equal(verified.matchingCatalogHash,true)
 assert.equal(verified.academicApprovalGranted,false)
 assert.equal(verified.academicQuestionsReviewed,false)
 fs.writeFileSync(pdf,Buffer.from('%PDF-'+ 'tampered'.repeat(400)))
 await assert.rejects(verifyCachedPdf('catalog-9',pdf,entry),/HASH_MISMATCH/)
 fs.writeFileSync(pdf,Buffer.from('FAKE-'+ 'example'.repeat(400)))
 await assert.rejects(verifyCachedPdf('catalog-9',pdf,entry),/INVALID_SOURCE_PDF_SIGNATURE/)
})
