// paperTemplates.js — Visual Presets for ASSPS Paper Generator
export const PAPER_TEMPLATES = [
  {
    id: 'academic',
    label: 'Academic Navy',
    desc: 'Formal navy rules and balanced academic typography',
    accent: '#123b67',
    accentSoft: '#eaf2fa',
    border: '#9eb6cf',
    headerStyle: 'standard',
    badgeBg: '#123b67',
    badgeText: '#ffffff',
    fontFamily: "'Times New Roman', serif",
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'modern',
    label: 'Modern Cyan',
    desc: 'Fresh cyan band with crisp sans-serif structure',
    accent: '#075985',
    accentSoft: '#e8f7fc',
    border: '#7fc5df',
    headerStyle: 'banded',
    badgeBg: '#075985',
    badgeText: '#ffffff',
    fontFamily: 'Arial, sans-serif',
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'emerald',
    label: 'Emerald Fresh',
    desc: 'Calm green accents with generous white space',
    accent: '#06695b',
    accentSoft: '#e6f7f3',
    border: '#88c9bc',
    headerStyle: 'standard',
    badgeBg: '#06695b',
    badgeText: '#ffffff',
    fontFamily: 'Calibri, sans-serif',
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'gold',
    label: 'Royal Gold',
    desc: 'Warm gold details on a clean white sheet',
    accent: '#9a6a00',
    accentSoft: '#fff8df',
    border: '#d6bd72',
    headerStyle: 'bordered',
    badgeBg: '#9a6a00',
    badgeText: '#ffffff',
    fontFamily: "'Times New Roman', serif",
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'coral',
    label: 'Coral Studio',
    desc: 'Contemporary coral accents and clean geometry',
    accent: '#c2410c',
    accentSoft: '#fff1ec',
    border: '#fdba74',
    headerStyle: 'modern',
    badgeBg: '#c2410c',
    badgeText: '#ffffff',
    fontFamily: 'Georgia, serif',
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'violet',
    label: 'Violet Scholar',
    desc: 'Refined violet details with a scholarly serif heading',
    accent: '#5b21b6',
    accentSoft: '#f5f3ff',
    border: '#c4b5fd',
    headerStyle: 'standard',
    badgeBg: '#5b21b6',
    badgeText: '#ffffff',
    fontFamily: 'Georgia, serif',
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'minimal',
    label: 'Minimal Monochrome',
    desc: 'Centered monochrome masthead with fine rules',
    accent: '#18181b',
    accentSoft: '#f4f4f5',
    border: '#d4d4d8',
    headerStyle: 'minimal',
    badgeBg: '#18181b',
    badgeText: '#ffffff',
    fontFamily: "'Times New Roman', serif",
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
  {
    id: 'editorial',
    label: 'Editorial Slate',
    desc: 'Left-aligned editorial masthead and slate examination strip',
    accent: '#334155',
    accentSoft: '#f1f5f9',
    border: '#94a3b8',
    headerStyle: 'editorial',
    badgeBg: '#334155',
    badgeText: '#ffffff',
    fontFamily: "'Times New Roman', serif",
    urduFont: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif",
  },
]

export function getTemplatePreset(templateId = 'academic') {
  return PAPER_TEMPLATES.find(t => t.id === templateId) || PAPER_TEMPLATES[0]
}
